import type { ToolSearchDoc } from './types'

export const TOOLS_CATALOG: ToolSearchDoc[] = [
  {
    kind: 'tool',
    slug: 'funding-calculators',
    href: '/funding-calculators',
    title: 'Funding Calculators',
    description: 'MUDRA loan, CGTMSE cover, PMEGP subsidy and EMI — instant estimates.',
    keywords: ['mudra', 'cgtmse', 'pmegp', 'emi', 'loan', 'subsidy', 'calculator', 'funding'],
  },
  {
    kind: 'tool',
    slug: 'get-funded',
    href: '/get-funded',
    title: 'Scheme Finder',
    description: 'Match yourself to government schemes based on budget, sector and category.',
    keywords: ['scheme', 'government', 'finder', 'subsidy', 'grant', 'pmegp', 'startup india'],
  },
  {
    kind: 'tool',
    slug: 'funding-radar',
    href: '/funding-radar',
    title: 'Startup Funding Radar',
    description: '65+ real Indian startup deals FY22–24 — filter by sector, stage, and city.',
    keywords: ['startup', 'funding', 'deals', 'vc', 'investors', 'series a', 'seed', 'radar'],
  },
  {
    kind: 'tool',
    slug: 'compliance-map',
    href: '/compliance-map',
    title: 'License & Compliance Map',
    description: 'Every license you need, cost, and processing time — for 9 common Indian business types.',
    keywords: ['license', 'compliance', 'gst', 'fssai', 'msme', 'regulation', 'registration'],
  },
  {
    kind: 'tool',
    slug: 'competitor-intel',
    href: '/competitor-intel',
    title: 'Competitor Intelligence',
    description: 'Scan 15 business categories in any Indian city — incumbent density, gap scores.',
    keywords: ['competitor', 'intelligence', 'city', 'market gap', 'density', 'incumbent'],
  },
  {
    kind: 'tool',
    slug: 'export-finder',
    href: '/export-finder',
    title: 'Export Opportunity Finder',
    description: '25 SME-accessible export categories with FY24 data — value, growth, top markets.',
    keywords: ['export', 'sme', 'trade', 'international', 'shipping', 'customs'],
  },
  {
    kind: 'tool',
    slug: 'supply-chain',
    href: '/supply-chain',
    title: 'Supply Chain Flow — Solar Maintenance',
    description: 'Interactive supply chain map for solar maintenance — suppliers, costs, margins.',
    keywords: ['supply chain', 'solar', 'maintenance', 'flow', 'suppliers'],
  },
  {
    kind: 'tool',
    slug: 'signal-radar',
    href: '/signal-radar',
    title: 'Signal Radar',
    description: 'Live intelligence from 20+ sources — YourStory, Inc42, Reddit, HN, scored by velocity.',
    keywords: ['signal', 'trends', 'news', 'reddit', 'hn', 'yourstory', 'inc42', 'live'],
  },
  {
    kind: 'tool',
    slug: 'dpiit-lookup',
    href: '/dpiit-lookup',
    title: 'DPIIT Competitor Lookup',
    description: '300+ DPIIT-recognized startups — filter by sector, state, funding stage.',
    keywords: ['dpiit', 'startup', 'recognized', 'lookup', 'competitor', 'india'],
  },
  {
    kind: 'tool',
    slug: 'local-radar',
    href: '/local-radar',
    title: 'Local Market Radar',
    description: 'City-level market intelligence: how many businesses exist, survival, entry velocity.',
    keywords: ['local', 'city', 'market', 'mca', 'udyam', 'gstin', 'google places'],
  },
  {
    kind: 'tool',
    slug: 'sector-pulse',
    href: '/sector-pulse',
    title: 'India Sector Pulse',
    description: '8-signal vitality index for 30 sectors — McKinsey-style economic health snapshot.',
    keywords: ['sector', 'pulse', 'mckinsey', 'index', 'vitality', 'economy', 'rbi'],
  },
  {
    kind: 'tool',
    slug: 'tender-search',
    href: '/tender-search',
    title: 'Government Tender Search',
    description: 'Live tenders from GeM, CPPP, MahaTenders — search active government contracts.',
    keywords: ['tender', 'gem', 'cppp', 'government', 'contracts', 'l1', 'bid'],
  },
  {
    kind: 'tool',
    slug: 'screener',
    href: '/screener',
    title: 'India KPI Screener',
    description: 'Sector KPIs for 75+ listed Indian companies — GNPA, NIM, VNB margin, RevPAR.',
    keywords: ['kpi', 'screener', 'nse', 'bse', 'listed', 'banks', 'pharma', 'hotels'],
  },
  {
    kind: 'tool',
    slug: 'capex-tracker',
    href: '/capex-tracker',
    title: 'Capex & Promise Tracker',
    description: 'Did the ₹500 Cr capex actually get spent? Track NSE-listed company promises vs. delivery.',
    keywords: ['capex', 'promise', 'tracker', 'nse', 'listed', 'concall', 'annual report'],
  },
  {
    kind: 'tool',
    slug: 'opportunity-finder',
    href: '/opportunity-finder',
    title: 'Opportunity Finder',
    description: 'Find ideas tailored to your budget, skills, and time commitment.',
    keywords: ['opportunity', 'finder', 'matcher', 'quiz', 'recommend'],
  },
  {
    kind: 'tool',
    slug: 'hyperlocal-opportunity',
    href: '/hyperlocal-opportunity',
    title: 'Hyperlocal Opportunity Map',
    description: 'Map of underserved demand at the neighborhood level across Indian cities.',
    keywords: ['hyperlocal', 'map', 'neighborhood', 'demand', 'underserved', 'h3'],
  },
  {
    kind: 'tool',
    slug: 'incentives',
    href: '/incentives',
    title: 'State Incentives',
    description: 'State-by-state incentives, subsidies and capital support for new businesses.',
    keywords: ['state', 'incentives', 'subsidy', 'capital support', 'msme'],
  },
  {
    kind: 'tool',
    slug: 'policy-pulse',
    href: '/policy-pulse',
    title: 'Policy Pulse',
    description: 'What changed in policy this week — and which businesses it touches.',
    keywords: ['policy', 'budget', 'rbi', 'sebi', 'regulation', 'pulse'],
  },
]
