// Udyam Registration data via data.gov.in API
// Dataset: "List of MSME Registered Units under UDYAM"
// Resource ID: 8b68ae56-84cf-4728-a0a6-1be11028dea7
// 39.4M+ records, updated daily. Required filters: State + District.
// Activities field contains NIC5DigitId as JSON array.
//
// Priority: preprocessed file (public/data/udyam/summary.json) > live API
// Run scripts/fetch-udyam.mjs to regenerate the preprocessed file.

import { readFile } from 'fs/promises'
import path from 'path'
import type { YearCount } from './types'

const RESOURCE_ID = '8b68ae56-84cf-4728-a0a6-1be11028dea7'

interface UdyamRecord {
  State?: string
  District?: string
  RegistrationDate?: string   // DD/MM/YYYY
  EnterpriseName?: string
  Activities?: string          // JSON: [{NIC5DigitId, Description}]
  [key: string]: string | number | undefined
}

interface ApiResponse {
  records?: UdyamRecord[]
  total?: number
  status?: string
  message?: string
}

export interface UdyamResult {
  district: string
  nicCode: string
  byYear: Record<number, number>
  totalCount: number
  trajectory: YearCount[]
  source: 'api' | 'estimated' | 'unavailable'
  note?: string
}

function parseYear(dateStr: string): number | null {
  const parts = dateStr.split('/')
  if (parts.length !== 3) return null
  const year = parseInt(parts[2])
  return year >= 2019 && year <= new Date().getFullYear() ? year : null
}

function matchesNic(activitiesJson: string | undefined, nicCode: string): boolean {
  if (!activitiesJson) return true
  try {
    const activities: { NIC5DigitId: string }[] = JSON.parse(activitiesJson)
    const prefix = nicCode.slice(0, 2)
    return activities.some(a => a.NIC5DigitId?.startsWith(prefix))
  } catch { return false }
}

// Load from preprocessed summary.json (generated by scripts/fetch-udyam.mjs)
async function loadFromFile(city: string, nicCode: string): Promise<UdyamResult | null> {
  try {
    const filePath = path.join(process.cwd(), 'public', 'data', 'udyam', 'summary.json')
    const raw = await readFile(filePath, 'utf-8')
    const data = JSON.parse(raw)

    const nicPrefix = nicCode.slice(0, 2)
    const cityData = data.byCityNicYear?.[city]
    if (!cityData) return null

    const nicData: Record<string, number> = cityData[nicPrefix] ?? {}
    if (Object.keys(nicData).length === 0) {
      // NIC not found — sum all NIC divisions as fallback
      const allByYear: Record<number, number> = {}
      for (const nicYears of Object.values(cityData) as Record<string, number>[]) {
        for (const [y, c] of Object.entries(nicYears)) {
          const year = parseInt(y)
          allByYear[year] = (allByYear[year] ?? 0) + c
        }
      }
      const totalCount = Object.values(allByYear).reduce((a, b) => a + b, 0)
      const trajectory: YearCount[] = Object.entries(allByYear)
        .map(([y, c]) => ({ year: parseInt(y), count: c, source: 'udyam' as const }))
        .sort((a, b) => a.year - b.year)
      return {
        district: city, nicCode, byYear: allByYear, totalCount, trajectory,
        source: 'estimated',
        note: `NIC ${nicPrefix} not in file — all-sector MSME count for ${city}`,
      }
    }

    const byYear: Record<number, number> = {}
    for (const [y, c] of Object.entries(nicData)) byYear[parseInt(y)] = c
    const totalCount = Object.values(byYear).reduce((a, b) => a + b, 0)
    const trajectory: YearCount[] = Object.entries(byYear)
      .map(([y, c]) => ({ year: parseInt(y), count: c, source: 'udyam' as const }))
      .sort((a, b) => a.year - b.year)

    return {
      district: city, nicCode, byYear, totalCount, trajectory,
      source: 'estimated',
      note: `Preprocessed Udyam data — NIC ${nicPrefix} MSMEs in ${city}`,
    }
  } catch { return null }
}

export async function fetchUdyamData(
  state: string,
  district: string,
  nicCode: string
): Promise<UdyamResult> {
  // 1. Try preprocessed file first (works in production without API access)
  const fromFile = await loadFromFile(district, nicCode)
  if (fromFile) return fromFile

  // 2. Fall back to live API
  const apiKey = process.env.DATA_GOV_IN_API_KEY
  if (!apiKey) {
    return {
      district, nicCode,
      byYear: {}, totalCount: 0,
      trajectory: [],
      source: 'unavailable',
      note: 'Set DATA_GOV_IN_API_KEY env var (free at data.gov.in) to enable Udyam district-level data',
    }
  }

  const nicPrefix = nicCode.slice(0, 2)
  const params = new URLSearchParams({
    'api-key': apiKey,
    'format': 'json',
    'limit': '500',
    'filters[State]': state.toUpperCase(),
    'filters[District]': district.toUpperCase(),
  })

  try {
    const res = await fetch(
      `https://api.data.gov.in/resource/${RESOURCE_ID}?${params}`,
      { next: { revalidate: 86400 }, headers: { 'User-Agent': 'BusinessIdeasBot/1.0' } }
    )
    if (!res.ok) {
      return { district, nicCode, byYear: {}, totalCount: 0, trajectory: [], source: 'unavailable', note: `API error: ${res.status}` }
    }

    const data: ApiResponse = await res.json()
    const records = data.records ?? []

    const byYear: Record<number, number> = {}
    let matchedCount = 0

    for (const r of records) {
      if (!matchesNic(r.Activities, nicPrefix)) continue
      const year = r.RegistrationDate ? parseYear(r.RegistrationDate) : null
      if (!year) continue
      byYear[year] = (byYear[year] ?? 0) + 1
      matchedCount++
    }

    if (matchedCount === 0 && records.length > 0) {
      for (const r of records) {
        const year = r.RegistrationDate ? parseYear(r.RegistrationDate) : null
        if (!year) continue
        byYear[year] = (byYear[year] ?? 0) + 1
      }
      const totalCount = Object.values(byYear).reduce((a, b) => a + b, 0)
      const trajectory: YearCount[] = Object.entries(byYear)
        .map(([y, c]) => ({ year: parseInt(y), count: c, source: 'udyam' as const }))
        .sort((a, b) => a.year - b.year)
      return {
        district, nicCode, byYear, totalCount, trajectory, source: 'api',
        note: `NIC ${nicPrefix} not found in sample — showing all district MSMEs (${data.total?.toLocaleString()} total in ${district})`,
      }
    }

    const totalCount = Object.values(byYear).reduce((a, b) => a + b, 0)
    const trajectory: YearCount[] = Object.entries(byYear)
      .map(([y, c]) => ({ year: parseInt(y), count: c, source: 'udyam' as const }))
      .sort((a, b) => a.year - b.year)

    return {
      district, nicCode, byYear, totalCount, trajectory, source: 'api',
      note: `${matchedCount} NIC-${nicPrefix} MSMEs in ${district} (from ${data.total?.toLocaleString()} total district registrations)`,
    }
  } catch (e) {
    return {
      district, nicCode,
      byYear: {}, totalCount: 0,
      trajectory: [],
      source: 'unavailable',
      note: `Request failed: ${e instanceof Error ? e.message : 'unknown error'}`,
    }
  }
}
