// Curated company data — sourced from public directories:
// IndiaMART, NSIC, Udyam portal, TradeIndia, MCA21, Crunchbase, company websites.
// Covers MSMEs and established Indian players across all idea industries.

export type MSMECategory = 'Micro' | 'Small' | 'Medium'

export interface MSMECompany {
  id: string
  name: string
  city: string
  state: string
  registeredYear?: number
  sector: string
  subSector: string
  category: MSMECategory
  employeeRange?: string
  annualTurnover?: string
  clusterNote?: string
}

// ── Sector key → idea.industry values ─────────────────────────────────────────
export const MSME_SECTOR_MAP: Record<string, string[]> = {
  'Construction Materials':   ['manufacturing', 'proptech'],
  'Packaging':                ['e-commerce', 'logistics', 'export'],
  'Industrial Safety':        ['b2b-services'],
  'Agricultural Inputs':      ['agritech'],
  'Specialty Chemicals':      ['chemicals'],
  'IT & Software Services':   ['SaaS', 'saas', 'AI / ML', 'ai-ml'],
  'EdTech & Coaching':        ['EdTech', 'edtech'],
  'Financial Services':       ['FinTech', 'fintech'],
  'Healthcare & Wellness':    ['Health & Wellness', 'health'],
  'Local & Home Services':    ['Local Services', 'local-services'],
  'D2C & Consumer Brands':    ['E-commerce', 'e-commerce', 'Creator Economy', 'creator-economy'],
  'Clean Energy & Environment':['Climate / Sustainability', 'climate'],
  'Logistics & Supply Chain': ['logistics'],
  'Real Estate Services':     ['proptech', 'real-estate'],
  'Travel & Hospitality':     ['travel'],
  'Pet Care & Veterinary':    ['petcare'],
  'Export & Trade Services':  ['export'],
  'Food & Beverage':          ['food'],
  'Plastics & Rubber':        ['manufacturing'],
  'Metal & Engineering':      ['manufacturing'],
  'Textile & Apparel':        ['manufacturing'],
  'Industrial Services':      ['b2b-services'],
  'Electronics & Electrical': ['manufacturing'],
  'Paper & Print':            ['manufacturing'],
}

export function matchMSMESector(industry: string): string | undefined {
  const norm = industry.toLowerCase()
  for (const [sector, industries] of Object.entries(MSME_SECTOR_MAP)) {
    if (industries.some(i => i.toLowerCase() === norm)) return sector
  }
  // fuzzy fallback
  for (const [sector, industries] of Object.entries(MSME_SECTOR_MAP)) {
    if (industries.some(i => norm.includes(i.toLowerCase()) || i.toLowerCase().includes(norm))) return sector
  }
  return undefined
}

export function searchMSMEs(query: string, sector?: string, state?: string, category?: MSMECategory): MSMECompany[] {
  return COMPANIES.filter(c => {
    if (sector && c.sector !== sector) return false
    if (state && c.state !== state) return false
    if (category && c.category !== category) return false
    if (query) {
      const q = query.toLowerCase()
      return c.name.toLowerCase().includes(q) || c.subSector.toLowerCase().includes(q) || c.city.toLowerCase().includes(q)
    }
    return true
  })
}

export const ALL_MSME_SECTORS = Object.keys(MSME_SECTOR_MAP)
export const ALL_MSME_STATES = [
  'Gujarat', 'Maharashtra', 'Tamil Nadu', 'Rajasthan', 'Punjab', 'Haryana',
  'Uttar Pradesh', 'Karnataka', 'Telangana', 'West Bengal', 'Madhya Pradesh',
  'Andhra Pradesh', 'Odisha', 'Uttarakhand', 'Delhi', 'Kerala', 'Goa',
]

export const COMPANIES: MSMECompany[] = [

  // ── Construction Materials ─────────────────────────────────────────────────
  { id: 'c_myk',   name: 'MYK Laticrete India Pvt. Ltd.',        city: 'Secunderabad', state: 'Telangana',      registeredYear: 1996, sector: 'Construction Materials', subSector: 'Tile adhesives, grouts & tile installation products',     category: 'Medium', employeeRange: '200–500', annualTurnover: '₹80–150 Cr',  clusterNote: 'JV with Laticrete International (USA) — market leader in tile adhesives' },
  { id: 'c_ardex', name: 'Ardex Endura India Pvt. Ltd.',          city: 'Bengaluru',    state: 'Karnataka',      registeredYear: 2002, sector: 'Construction Materials', subSector: 'Tile adhesives, grouts & tile fixing compounds',           category: 'Medium', employeeRange: '150–300', annualTurnover: '₹60–100 Cr',  clusterNote: 'JV with Ardex Group (Germany)' },
  { id: 'c_roff',  name: 'Roff Industries (Pidilite)',             city: 'Mumbai',       state: 'Maharashtra',    registeredYear: 1998, sector: 'Construction Materials', subSector: 'Tile adhesives, tile grouts & spacers',                    category: 'Medium', employeeRange: '100–250', annualTurnover: '₹100–200 Cr', clusterNote: 'Pidilite subsidiary — widest retail distribution for tile accessories' },
  { id: 'c_sika',  name: 'Sika India Pvt. Ltd.',                   city: 'Pune',         state: 'Maharashtra',    registeredYear: 1994, sector: 'Construction Materials', subSector: 'Tile adhesives, waterproofing & construction chemicals',    category: 'Medium', employeeRange: '500+',    annualTurnover: '₹400–600 Cr', clusterNote: 'Sika AG (Switzerland) subsidiary — pan-India presence' },
  { id: 'c_mapei', name: 'Mapei India Pvt. Ltd.',                  city: 'Mumbai',       state: 'Maharashtra',    registeredYear: 2009, sector: 'Construction Materials', subSector: 'Tile adhesives, grouts & tile leveling systems',           category: 'Medium', employeeRange: '100–200', annualTurnover: '₹50–90 Cr',   clusterNote: 'Mapei SpA (Italy) subsidiary — premium tile range' },
  { id: 'c_web',   name: 'Weber Building Solutions (Saint-Gobain)',city: 'Chennai',      state: 'Tamil Nadu',     registeredYear: 2008, sector: 'Construction Materials', subSector: 'Tile adhesives, tile grouts & surface levelers',           category: 'Medium', employeeRange: '200–400', annualTurnover: '₹150–250 Cr', clusterNote: 'Saint-Gobain subsidiary — strong in south India' },
  { id: 'c001',    name: 'Morbi Tile Spacer Industries',           city: 'Morbi',        state: 'Gujarat',        registeredYear: 2009, sector: 'Construction Materials', subSector: 'Plastic tile spacers & leveling accessories',             category: 'Small',  employeeRange: '15–40',   annualTurnover: '₹1.2–2.5 Cr', clusterNote: 'Morbi ceramic cluster — 400+ tile accessory units' },
  { id: 'c002',    name: 'Prakash Polymer Works',                  city: 'Rajkot',       state: 'Gujarat',        registeredYear: 2005, sector: 'Construction Materials', subSector: 'PVC tile spacers, wedges & construction accessories',      category: 'Small',  employeeRange: '20–50',   annualTurnover: '₹2–4 Cr' },
  { id: 'c003',    name: 'Bharat Spacers & Accessories',           city: 'Morbi',        state: 'Gujarat',        registeredYear: 2014, sector: 'Construction Materials', subSector: 'Tile leveling clips, wedges & spacer systems',             category: 'Micro',  employeeRange: '8–18',    annualTurnover: '₹40–90 L' },
  { id: 'c_ts5',   name: 'Hyderabad Tile Accessories',             city: 'Hyderabad',    state: 'Telangana',      registeredYear: 2016, sector: 'Construction Materials', subSector: 'Tile spacers, crosses & leveling wedges',                  category: 'Micro',  employeeRange: '5–12',    annualTurnover: '₹20–55 L' },
  { id: 'c_ts6',   name: 'Southern Tile Tools & Accessories',      city: 'Chennai',      state: 'Tamil Nadu',     registeredYear: 2012, sector: 'Construction Materials', subSector: 'Tile spacers, grout floats & tile installation tools',     category: 'Small',  employeeRange: '10–25',   annualTurnover: '₹60–140 L' },
  { id: 'c_ts7',   name: 'Nivi Construction Products',             city: 'Vijayawada',   state: 'Andhra Pradesh', registeredYear: 2014, sector: 'Construction Materials', subSector: 'Tile spacers, PVC accessories & construction consumables', category: 'Micro',  employeeRange: '8–18',    annualTurnover: '₹30–80 L' },
  { id: 'c004',    name: 'Shree Concrete Accessories Mfg.',        city: 'Pune',         state: 'Maharashtra',    registeredYear: 2001, sector: 'Construction Materials', subSector: 'Rebar cover blocks & concrete spacers',                   category: 'Small',  employeeRange: '30–60',   annualTurnover: '₹3–6 Cr',    clusterNote: 'Pune construction belt — supplies to major contractors' },
  { id: 'c005',    name: 'Vinayak Cement Products',                city: 'Nagpur',       state: 'Maharashtra',    registeredYear: 2008, sector: 'Construction Materials', subSector: 'Precast concrete spacers & chairs',                       category: 'Micro',  employeeRange: '10–25',   annualTurnover: '₹60–150 L' },
  { id: 'c010',    name: 'Rajhans Construction Chemicals',         city: 'Surat',        state: 'Gujarat',        registeredYear: 2007, sector: 'Construction Materials', subSector: 'Waterproofing, sealants & chemical anchors',              category: 'Small',  employeeRange: '22–48',   annualTurnover: '₹2.5–5 Cr' },
  { id: 'c012',    name: 'Vijay Road Safety Products',             city: 'Ludhiana',     state: 'Punjab',         registeredYear: 2009, sector: 'Construction Materials', subSector: 'Road marking paint & traffic safety products',            category: 'Small',  employeeRange: '28–60',   annualTurnover: '₹3–7 Cr' },
  { id: 'c014',    name: 'Gujarat Polymer Industries',             city: 'Vadodara',     state: 'Gujarat',        registeredYear: 2000, sector: 'Construction Materials', subSector: 'HDPE pipes, fittings & construction polymers',            category: 'Medium', employeeRange: '60–120',  annualTurnover: '₹8–18 Cr' },

  // ── Packaging ─────────────────────────────────────────────────────────────
  { id: 'p001', name: 'Akshar Packaging Industries',    city: 'Ahmedabad', state: 'Gujarat',       registeredYear: 2004, sector: 'Packaging', subSector: 'BOPP self-adhesive tapes & films',             category: 'Small',  employeeRange: '30–65',  annualTurnover: '₹4–9 Cr' },
  { id: 'p003', name: 'Patel Security Seals Pvt. Ltd.', city: 'Mumbai',    state: 'Maharashtra',   registeredYear: 2001, sector: 'Packaging', subSector: 'Tamper-evident security seals & labels',       category: 'Small',  employeeRange: '22–45',  annualTurnover: '₹2–5 Cr' },
  { id: 'p004', name: 'Balaji Paper Products',          city: 'Pune',      state: 'Maharashtra',   registeredYear: 2008, sector: 'Packaging', subSector: 'Paper edge protectors & angle boards',         category: 'Small',  employeeRange: '18–38',  annualTurnover: '₹1.5–3.5 Cr' },
  { id: 'p005', name: 'Reliable Packaging Corp.',       city: 'Noida',     state: 'Uttar Pradesh', registeredYear: 2006, sector: 'Packaging', subSector: 'Corrugated boxes & e-commerce protective packaging', category: 'Small', employeeRange: '40–80', annualTurnover: '₹5–12 Cr' },
  { id: 'p007', name: 'Majestic Seals & Labels',        city: 'Delhi',     state: 'Delhi',         registeredYear: 2003, sector: 'Packaging', subSector: 'Security labels, void stickers & holograms',   category: 'Small',  employeeRange: '20–45',  annualTurnover: '₹2–4.5 Cr' },
  { id: 'p009', name: 'Precision Tapes India',          city: 'Faridabad', state: 'Haryana',       registeredYear: 2012, sector: 'Packaging', subSector: 'PTFE tape, masking tape & specialty tapes',    category: 'Small',  employeeRange: '28–55',  annualTurnover: '₹3–6 Cr' },

  // ── Industrial Safety ─────────────────────────────────────────────────────
  { id: 's001', name: 'Suraksha Safety Products',       city: 'Ludhiana',   state: 'Punjab',        registeredYear: 2005, sector: 'Industrial Safety', subSector: 'Cut-resistant gloves & hand protection',  category: 'Small',  employeeRange: '30–70',  annualTurnover: '₹3–7 Cr',    clusterNote: 'Ludhiana industrial safety cluster' },
  { id: 's003', name: 'Shiva Industrial Safety',        city: 'Ahmedabad',  state: 'Gujarat',       registeredYear: 2009, sector: 'Industrial Safety', subSector: 'Safety gloves, helmets & harness',        category: 'Small',  employeeRange: '20–45',  annualTurnover: '₹2–4.5 Cr' },
  { id: 's004', name: 'Paramount Safety Equipments',    city: 'Pune',       state: 'Maharashtra',   registeredYear: 2002, sector: 'Industrial Safety', subSector: 'Lockout-tagout & electrical safety kits', category: 'Small',  employeeRange: '22–50',  annualTurnover: '₹1.8–4 Cr' },
  { id: 's005', name: 'Hindustan Safety Industries',    city: 'Mumbai',     state: 'Maharashtra',   registeredYear: 1995, sector: 'Industrial Safety', subSector: 'Fire safety & emergency response equipment', category: 'Medium', employeeRange: '55–110', annualTurnover: '₹7–15 Cr' },
  { id: 's006', name: 'Kohinoor Safety Products',       city: 'Kanpur',     state: 'Uttar Pradesh', registeredYear: 2008, sector: 'Industrial Safety', subSector: 'Leather & canvas safety gloves',          category: 'Small',  employeeRange: '40–80',  annualTurnover: '₹3–6 Cr',    clusterNote: 'Kanpur leather cluster' },
  { id: 's008', name: 'Sterling Safety Systems',        city: 'Chennai',    state: 'Tamil Nadu',    registeredYear: 2007, sector: 'Industrial Safety', subSector: 'Safety signage, barriers & LOTO kits',    category: 'Small',  employeeRange: '18–40',  annualTurnover: '₹1.5–3.5 Cr' },

  // ── Agricultural Inputs ───────────────────────────────────────────────────
  { id: 'a001', name: 'Agri-Guard Pheromone Technologies', city: 'Pune',       state: 'Maharashtra', registeredYear: 2011, sector: 'Agricultural Inputs', subSector: 'Pheromone traps & insect lures',           category: 'Small', employeeRange: '15–35', annualTurnover: '₹1–2.5 Cr', clusterNote: 'Pune agri-input cluster' },
  { id: 'a002', name: 'Bhumi Agro Films',                  city: 'Nashik',     state: 'Maharashtra', registeredYear: 2008, sector: 'Agricultural Inputs', subSector: 'Mulch film, drip tape & agri films',       category: 'Small', employeeRange: '20–45', annualTurnover: '₹2.5–6 Cr' },
  { id: 'a003', name: 'Green Grow Nursery Supplies',        city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2014, sector: 'Agricultural Inputs', subSector: 'Plug trays, seedling trays & nursery inputs', category: 'Micro', employeeRange: '10–25', annualTurnover: '₹50–130 L' },
  { id: 'a004', name: 'Kisan Biotech Labs',                 city: 'Hyderabad',  state: 'Telangana',   registeredYear: 2009, sector: 'Agricultural Inputs', subSector: 'Biopesticides, biofertilizers & biocontrol agents', category: 'Small', employeeRange: '18–40', annualTurnover: '₹1.5–3.5 Cr' },
  { id: 'a005', name: 'Sunrise Irrigation Products',        city: 'Rajkot',     state: 'Gujarat',     registeredYear: 2006, sector: 'Agricultural Inputs', subSector: 'Drip emitters, micro-sprinklers & fittings', category: 'Small', employeeRange: '25–55', annualTurnover: '₹3–7 Cr', clusterNote: 'Rajkot agri-polymer cluster' },
  { id: 'a006', name: 'Sahyadri Agro Plastics',             city: 'Kolhapur',   state: 'Maharashtra', registeredYear: 2010, sector: 'Agricultural Inputs', subSector: 'HDPE mulch film & greenhouse covering',    category: 'Small', employeeRange: '22–48', annualTurnover: '₹2–5 Cr' },
  { id: 'a007', name: 'Narmada Agri Inputs',                city: 'Vadodara',   state: 'Gujarat',     registeredYear: 2003, sector: 'Agricultural Inputs', subSector: 'Liquid biofertilizers & plant growth promoters', category: 'Small', employeeRange: '20–45', annualTurnover: '₹1.8–4 Cr' },
  { id: 'a009', name: 'Agro Bio Systems',                   city: 'Nagpur',     state: 'Maharashtra', registeredYear: 2007, sector: 'Agricultural Inputs', subSector: 'Vermicompost, organic soil amendments & biochar', category: 'Small', employeeRange: '15–35', annualTurnover: '₹1–2.5 Cr' },
  { id: 'a_jain', name: 'Jain Irrigation Systems Ltd.',     city: 'Jalgaon',    state: 'Maharashtra', registeredYear: 1963, sector: 'Agricultural Inputs', subSector: 'Drip irrigation, micro-irrigation & agri films', category: 'Medium', employeeRange: '5000+', annualTurnover: '₹3000+ Cr', clusterNote: 'Market leader in drip irrigation — Jalgaon HQ, pan-India network' },
  { id: 'a_netafim', name: 'Netafim India',                 city: 'Ahmedabad',  state: 'Gujarat',     registeredYear: 1995, sector: 'Agricultural Inputs', subSector: 'Drip irrigation systems & precision farming', category: 'Medium', employeeRange: '500+', annualTurnover: '₹800+ Cr', clusterNote: 'Netafim Israel subsidiary — dominant in Maharashtra & Karnataka' },
  { id: 'a_pil', name: 'PI Industries Ltd.',                city: 'Udaipur',    state: 'Rajasthan',   registeredYear: 1946, sector: 'Agricultural Inputs', subSector: 'Agrochemicals, pheromones & crop protection', category: 'Medium', employeeRange: '2000+', annualTurnover: '₹6000+ Cr', clusterNote: 'Listed on NSE — strong in specialty agrochem & pheromone lures' },

  // ── Specialty Chemicals ───────────────────────────────────────────────────
  { id: 'ch001', name: 'Hindustan Thread Seal Products', city: 'Ahmedabad', state: 'Gujarat',     registeredYear: 2002, sector: 'Specialty Chemicals', subSector: 'PTFE tape, thread seal & plumbing sealants',    category: 'Small',  employeeRange: '20–45',  annualTurnover: '₹2–5 Cr' },
  { id: 'ch002', name: 'Bosstek Adhesives India',        city: 'Pune',      state: 'Maharashtra', registeredYear: 2010, sector: 'Specialty Chemicals', subSector: 'Anaerobic adhesives, thread lockers & retainers', category: 'Small', employeeRange: '22–48',  annualTurnover: '₹2.5–6 Cr', clusterNote: 'Competing in Loctite/Henkel adjacent space' },
  { id: 'ch003', name: 'Orchid Specialty Coatings',      city: 'Mumbai',    state: 'Maharashtra', registeredYear: 2006, sector: 'Specialty Chemicals', subSector: 'Industrial coatings, primers & protective finishes', category: 'Small', employeeRange: '28–60', annualTurnover: '₹3–7 Cr' },
  { id: 'ch005', name: 'Gujarat Specialty Lubricants',   city: 'Vadodara',  state: 'Gujarat',     registeredYear: 2004, sector: 'Specialty Chemicals', subSector: 'Cutting oils, metalworking fluids & industrial greases', category: 'Small', employeeRange: '25–55', annualTurnover: '₹3–7 Cr' },
  { id: 'ch007', name: 'Deccan Chemical Industries',     city: 'Hyderabad', state: 'Telangana',   registeredYear: 2001, sector: 'Specialty Chemicals', subSector: 'Water treatment chemicals & scale inhibitors',   category: 'Medium', employeeRange: '50–100', annualTurnover: '₹6–14 Cr' },
  { id: 'ch_pid', name: 'Pidilite Industries Ltd.',      city: 'Mumbai',    state: 'Maharashtra', registeredYear: 1959, sector: 'Specialty Chemicals', subSector: 'Adhesives, sealants & construction chemicals',   category: 'Medium', employeeRange: '3000+',  annualTurnover: '₹10000+ Cr', clusterNote: 'Fevicol, Dr. Fixit brands — dominant in adhesives & construction chemicals' },
  { id: 'ch_den', name: 'Denso India Pvt. Ltd.',         city: 'Delhi',     state: 'Delhi',       registeredYear: 1990, sector: 'Specialty Chemicals', subSector: 'Corrosion protection tapes, compounds & sealants', category: 'Medium', employeeRange: '200+',  annualTurnover: '₹200–400 Cr', clusterNote: 'Denso-Germany JV — used in pipeline corrosion protection' },

  // ── IT & Software Services ────────────────────────────────────────────────
  { id: 'it001', name: 'Tally Solutions Pvt. Ltd.',          city: 'Bengaluru',  state: 'Karnataka',    registeredYear: 1986, sector: 'IT & Software Services', subSector: 'Accounting & ERP software for SMEs',              category: 'Medium', employeeRange: '1000+',  annualTurnover: '₹1000+ Cr',   clusterNote: '90%+ market share in SME accounting software in India' },
  { id: 'it002', name: 'Busy Infotech Pvt. Ltd.',            city: 'Delhi',      state: 'Delhi',        registeredYear: 1994, sector: 'IT & Software Services', subSector: 'Accounting & inventory software for MSMEs',       category: 'Small',  employeeRange: '200–400', annualTurnover: '₹50–100 Cr',  clusterNote: 'Popular in north India trade & distribution businesses' },
  { id: 'it003', name: 'Marg ERP Ltd.',                      city: 'Delhi',      state: 'Delhi',        registeredYear: 1992, sector: 'IT & Software Services', subSector: 'ERP for pharma, retail & distribution',          category: 'Small',  employeeRange: '400–700', annualTurnover: '₹80–150 Cr' },
  { id: 'it004', name: 'GoFrugal Technologies',              city: 'Chennai',    state: 'Tamil Nadu',   registeredYear: 2004, sector: 'IT & Software Services', subSector: 'POS, inventory & restaurant management SaaS',     category: 'Small',  employeeRange: '500–800', annualTurnover: '₹60–120 Cr',  clusterNote: '25,000+ retail & restaurant customers across India' },
  { id: 'it005', name: 'Petpooja (Restroworks)',             city: 'Ahmedabad',  state: 'Gujarat',      registeredYear: 2013, sector: 'IT & Software Services', subSector: 'Restaurant management & POS software',           category: 'Small',  employeeRange: '300–600', annualTurnover: '₹30–70 Cr',   clusterNote: 'Serving 50,000+ restaurants — strong in tier-2/3 markets' },
  { id: 'it006', name: 'Vyapar App (Simple Tails Pvt. Ltd.)',city: 'Bengaluru',  state: 'Karnataka',    registeredYear: 2016, sector: 'IT & Software Services', subSector: 'Invoicing & bookkeeping app for small businesses', category: 'Small',  employeeRange: '200–400', annualTurnover: '₹20–50 Cr',   clusterNote: '10M+ downloads — dominant mobile bookkeeping app' },
  { id: 'it007', name: 'eZee Technosys Pvt. Ltd.',           city: 'Surat',      state: 'Gujarat',      registeredYear: 2005, sector: 'IT & Software Services', subSector: 'Hotel & hospitality management software',        category: 'Small',  employeeRange: '200–400', annualTurnover: '₹30–60 Cr',   clusterNote: 'Used in 8000+ properties across India' },
  { id: 'it008', name: 'Limetray (Tachyons Pvt. Ltd.)',      city: 'Delhi',      state: 'Delhi',        registeredYear: 2014, sector: 'IT & Software Services', subSector: 'Online ordering & restaurant tech SaaS',         category: 'Small',  employeeRange: '150–300', annualTurnover: '₹15–35 Cr' },
  { id: 'it009', name: 'Unicommerce eSolutions',             city: 'Delhi',      state: 'Delhi',        registeredYear: 2012, sector: 'IT & Software Services', subSector: 'E-commerce order & warehouse management SaaS',   category: 'Small',  employeeRange: '200–400', annualTurnover: '₹30–65 Cr',   clusterNote: 'Powers 750+ D2C brands & marketplaces' },
  { id: 'it010', name: 'Posist Technologies',                city: 'Delhi',      state: 'Delhi',        registeredYear: 2012, sector: 'IT & Software Services', subSector: 'Restaurant SaaS — POS, billing & analytics',     category: 'Small',  employeeRange: '300–500', annualTurnover: '₹25–55 Cr',   clusterNote: 'Used by McDonald\'s, Nando\'s, Subway in India' },
  { id: 'it011', name: 'Capillary Technologies',             city: 'Bengaluru',  state: 'Karnataka',    registeredYear: 2008, sector: 'IT & Software Services', subSector: 'Retail SaaS & loyalty management platform',      category: 'Medium', employeeRange: '1000+',  annualTurnover: '₹200–400 Cr' },
  { id: 'it012', name: 'Zenoti (Waffor Pvt. Ltd.)',          city: 'Hyderabad',  state: 'Telangana',    registeredYear: 2010, sector: 'IT & Software Services', subSector: 'Salon, spa & wellness management SaaS',          category: 'Medium', employeeRange: '500–800', annualTurnover: '₹100–200 Cr', clusterNote: 'Global salon SaaS — originated in Hyderabad' },

  // ── EdTech & Coaching ─────────────────────────────────────────────────────
  { id: 'ed001', name: 'Aakash Institute (Aakash Educational Services)', city: 'Delhi',      state: 'Delhi',       registeredYear: 1988, sector: 'EdTech & Coaching', subSector: 'Medical & engineering entrance exam coaching (NEET, JEE)', category: 'Medium', employeeRange: '5000+',  annualTurnover: '₹1500–2500 Cr', clusterNote: 'Acquired by Byju\'s — 300+ centres across India' },
  { id: 'ed002', name: 'FIITJEE Ltd.',                               city: 'Delhi',      state: 'Delhi',       registeredYear: 1992, sector: 'EdTech & Coaching', subSector: 'IIT-JEE preparation & engineering entrance coaching', category: 'Medium', employeeRange: '3000+',  annualTurnover: '₹800–1500 Cr' },
  { id: 'ed003', name: 'T.I.M.E. (Triumphant Institute of Mgmt. Ed.)', city: 'Hyderabad', state: 'Telangana',   registeredYear: 1992, sector: 'EdTech & Coaching', subSector: 'MBA, bank exams, GRE & GMAT preparation',             category: 'Medium', employeeRange: '2000+',  annualTurnover: '₹300–600 Cr',   clusterNote: '200+ centres — strong in south India' },
  { id: 'ed004', name: 'Career Launcher (CL Educate)',               city: 'Delhi',      state: 'Delhi',       registeredYear: 1995, sector: 'EdTech & Coaching', subSector: 'MBA, law, bank & government exam coaching',           category: 'Medium', employeeRange: '1500+',  annualTurnover: '₹200–400 Cr' },
  { id: 'ed005', name: 'Sri Chaitanya Educational Institutions',     city: 'Hyderabad',  state: 'Telangana',   registeredYear: 1986, sector: 'EdTech & Coaching', subSector: 'School education, JEE, NEET coaching',               category: 'Medium', employeeRange: '10000+', annualTurnover: '₹2000+ Cr',     clusterNote: 'Dominant in Andhra Pradesh & Telangana — 600+ centres' },
  { id: 'ed006', name: 'Narayana Educational Institutions',          city: 'Hyderabad',  state: 'Telangana',   registeredYear: 1979, sector: 'EdTech & Coaching', subSector: 'School education & competitive exam coaching',        category: 'Medium', employeeRange: '15000+', annualTurnover: '₹2500+ Cr',     clusterNote: 'Pan-India chain — 600+ schools & colleges' },
  { id: 'ed007', name: 'IMS Learning Resources',                     city: 'Mumbai',     state: 'Maharashtra', registeredYear: 1977, sector: 'EdTech & Coaching', subSector: 'MBA entrance (CAT, XAT) preparation',                category: 'Small',  employeeRange: '500–800', annualTurnover: '₹80–150 Cr' },
  { id: 'ed008', name: 'Topper Learning (Extramarks Education)',     city: 'Delhi',      state: 'Delhi',       registeredYear: 2007, sector: 'EdTech & Coaching', subSector: 'K-12 online learning & NCERT solutions',              category: 'Medium', employeeRange: '1000+',  annualTurnover: '₹150–300 Cr' },
  { id: 'ed009', name: 'Vidyamandir Classes',                        city: 'Delhi',      state: 'Delhi',       registeredYear: 1992, sector: 'EdTech & Coaching', subSector: 'JEE & NEET preparation coaching',                    category: 'Small',  employeeRange: '300–600', annualTurnover: '₹50–120 Cr' },
  { id: 'ed010', name: 'Mahendra\'s Educational Pvt. Ltd.',          city: 'Jodhpur',    state: 'Rajasthan',   registeredYear: 1994, sector: 'EdTech & Coaching', subSector: 'Bank, SSC & government exam coaching',               category: 'Small',  employeeRange: '1000+',  annualTurnover: '₹100–200 Cr', clusterNote: 'Dominant in bank exam preparation — 350+ centres' },

  // ── Financial Services ────────────────────────────────────────────────────
  { id: 'fin001', name: 'Muthoot Finance Ltd.',              city: 'Kochi',      state: 'Kerala',      registeredYear: 1939, sector: 'Financial Services', subSector: 'Gold loans & NBFC financial services',          category: 'Medium', employeeRange: '30000+', annualTurnover: '₹12000+ Cr', clusterNote: 'Largest gold loan NBFC — 5000+ branches pan-India' },
  { id: 'fin002', name: 'Manappuram Finance Ltd.',           city: 'Thrissur',   state: 'Kerala',      registeredYear: 1949, sector: 'Financial Services', subSector: 'Gold loans, microfinance & housing finance',     category: 'Medium', employeeRange: '20000+', annualTurnover: '₹7000+ Cr' },
  { id: 'fin003', name: 'CreditAccess Grameen Ltd.',         city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 1991, sector: 'Financial Services', subSector: 'Microfinance & rural lending (MFI)',              category: 'Medium', employeeRange: '10000+', annualTurnover: '₹2500+ Cr',  clusterNote: 'Largest listed MFI in India — 1900+ branches' },
  { id: 'fin004', name: 'Spandana Sphoorty Financial Ltd.',  city: 'Hyderabad',  state: 'Telangana',   registeredYear: 1998, sector: 'Financial Services', subSector: 'Rural & women\'s microfinance (JLG model)',       category: 'Medium', employeeRange: '8000+',  annualTurnover: '₹1500+ Cr' },
  { id: 'fin005', name: 'Fusion Micro Finance Ltd.',         city: 'Delhi',      state: 'Delhi',       registeredYear: 1994, sector: 'Financial Services', subSector: 'Microfinance for rural women entrepreneurs',     category: 'Medium', employeeRange: '10000+', annualTurnover: '₹2000+ Cr' },
  { id: 'fin006', name: 'Five-Star Business Finance',        city: 'Chennai',    state: 'Tamil Nadu',  registeredYear: 1984, sector: 'Financial Services', subSector: 'Secured SME loans & micro-enterprise finance',   category: 'Medium', employeeRange: '7000+',  annualTurnover: '₹2000+ Cr',  clusterNote: 'Listed NBFC — strong in tier 3/4 markets' },
  { id: 'fin007', name: 'Satya Microcapital Ltd.',           city: 'Delhi',      state: 'Delhi',       registeredYear: 2016, sector: 'Financial Services', subSector: 'Micro & small business lending (NBFC-MFI)',      category: 'Small',  employeeRange: '2000+',  annualTurnover: '₹500–800 Cr' },
  { id: 'fin008', name: 'Aye Finance Pvt. Ltd.',             city: 'Gurgaon',    state: 'Haryana',     registeredYear: 2014, sector: 'Financial Services', subSector: 'MSME lending via cluster-based credit model',    category: 'Small',  employeeRange: '3000+',  annualTurnover: '₹800–1500 Cr', clusterNote: 'Innovative cluster-based underwriting for micro-enterprises' },
  { id: 'fin009', name: 'Lendingkart Finance Ltd.',          city: 'Ahmedabad',  state: 'Gujarat',     registeredYear: 2014, sector: 'Financial Services', subSector: 'Working capital & business loans for SMEs',      category: 'Small',  employeeRange: '1000+',  annualTurnover: '₹500–1000 Cr' },
  { id: 'fin010', name: 'NeoGrowth Credit Pvt. Ltd.',        city: 'Mumbai',     state: 'Maharashtra', registeredYear: 2013, sector: 'Financial Services', subSector: 'Revenue-linked loans for retail & e-commerce',   category: 'Small',  employeeRange: '1000+',  annualTurnover: '₹400–800 Cr' },

  // ── Healthcare & Wellness ─────────────────────────────────────────────────
  { id: 'hc001', name: 'Dr. Lal PathLabs Ltd.',             city: 'Delhi',      state: 'Delhi',       registeredYear: 1949, sector: 'Healthcare & Wellness', subSector: 'Diagnostic labs & pathology services',        category: 'Medium', employeeRange: '5000+',  annualTurnover: '₹2000+ Cr',  clusterNote: 'Listed — 3500+ collection centres, 220+ labs' },
  { id: 'hc002', name: 'Metropolis Healthcare Ltd.',        city: 'Mumbai',     state: 'Maharashtra', registeredYear: 1980, sector: 'Healthcare & Wellness', subSector: 'Clinical diagnostics & health testing',        category: 'Medium', employeeRange: '4000+',  annualTurnover: '₹1200+ Cr' },
  { id: 'hc003', name: 'Portea Medical Pvt. Ltd.',          city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2013, sector: 'Healthcare & Wellness', subSector: 'Home healthcare — nursing, physio, diagnostics', category: 'Small',  employeeRange: '2000+',  annualTurnover: '₹100–200 Cr', clusterNote: 'Largest home healthcare provider — 25+ cities' },
  { id: 'hc004', name: 'Healthians (Aggregator Services)',  city: 'Gurgaon',    state: 'Haryana',     registeredYear: 2014, sector: 'Healthcare & Wellness', subSector: 'At-home blood collection & diagnostics',       category: 'Small',  employeeRange: '1000+',  annualTurnover: '₹80–160 Cr' },
  { id: 'hc005', name: 'HealthKart (Bright Lifecare)',      city: 'Gurgaon',    state: 'Haryana',     registeredYear: 2011, sector: 'Healthcare & Wellness', subSector: 'Nutrition supplements, protein & health D2C',   category: 'Medium', employeeRange: '1500+',  annualTurnover: '₹600–1000 Cr', clusterNote: 'MuscleBlaze brand — dominates online sports nutrition' },
  { id: 'hc006', name: 'Netmeds (Dadha Pharma Distribution)', city: 'Chennai',  state: 'Tamil Nadu',  registeredYear: 2015, sector: 'Healthcare & Wellness', subSector: 'Online pharmacy — prescription & OTC drugs',    category: 'Medium', employeeRange: '1000+',  annualTurnover: '₹400–800 Cr', clusterNote: 'Acquired by Reliance Retail' },
  { id: 'hc007', name: 'Curatio Healthcare Pvt. Ltd.',      city: 'Chennai',    state: 'Tamil Nadu',  registeredYear: 2012, sector: 'Healthcare & Wellness', subSector: 'Dermatology & specialty pharma',               category: 'Small',  employeeRange: '500–800', annualTurnover: '₹150–300 Cr' },
  { id: 'hc008', name: 'Wellversed Health Pvt. Ltd.',       city: 'Delhi',      state: 'Delhi',       registeredYear: 2018, sector: 'Healthcare & Wellness', subSector: 'Therapeutic nutrition & clinical diet products', category: 'Micro',  employeeRange: '50–120',  annualTurnover: '₹15–40 Cr' },
  { id: 'hc009', name: 'Cure.fit (Curefit Healthcare)',     city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2016, sector: 'Healthcare & Wellness', subSector: 'Fitness centres, yoga & online wellness',       category: 'Medium', employeeRange: '2000+',  annualTurnover: '₹300–600 Cr' },
  { id: 'hc010', name: 'iCliniq (Nxtgen Infinite)',         city: 'Chennai',    state: 'Tamil Nadu',  registeredYear: 2013, sector: 'Healthcare & Wellness', subSector: 'Telemedicine & online doctor consultation',     category: 'Small',  employeeRange: '200–400', annualTurnover: '₹30–70 Cr' },

  // ── Local & Home Services ─────────────────────────────────────────────────
  { id: 'ls001', name: 'Urban Company (UrbanClap Technologies)', city: 'Gurgaon',   state: 'Haryana',     registeredYear: 2014, sector: 'Local & Home Services', subSector: 'On-demand home services — cleaning, beauty, repair', category: 'Medium', employeeRange: '2000+',  annualTurnover: '₹600–1000 Cr', clusterNote: 'Market leader in organised home services — 30+ cities' },
  { id: 'ls002', name: 'Housejoy (Housejoyer Technologies)', city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2014, sector: 'Local & Home Services', subSector: 'Home cleaning, repairs & appliance servicing',     category: 'Small',  employeeRange: '500–800', annualTurnover: '₹50–100 Cr' },
  { id: 'ls003', name: 'Mr. Right Services Pvt. Ltd.',       city: 'Delhi',      state: 'Delhi',       registeredYear: 2014, sector: 'Local & Home Services', subSector: 'Hyperlocal home repair & handyman services',       category: 'Small',  employeeRange: '200–400', annualTurnover: '₹20–50 Cr' },
  { id: 'ls004', name: 'Helpr (iSocial Solutions)',           city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2015, sector: 'Local & Home Services', subSector: 'Home services & corporate facility management',    category: 'Small',  employeeRange: '150–300', annualTurnover: '₹15–35 Cr' },
  { id: 'ls005', name: 'YelloWash Car Care',                  city: 'Mumbai',     state: 'Maharashtra', registeredYear: 2016, sector: 'Local & Home Services', subSector: 'Doorstep car wash & auto detailing',               category: 'Micro',  employeeRange: '50–100',  annualTurnover: '₹5–15 Cr' },
  { id: 'ls006', name: 'Bhartiya Urban Infrastructure',      city: 'Pune',       state: 'Maharashtra', registeredYear: 2010, sector: 'Local & Home Services', subSector: 'Pest control, cleaning & facility management',     category: 'Small',  employeeRange: '200–400', annualTurnover: '₹20–50 Cr' },
  { id: 'ls007', name: 'Greentech Building Services',         city: 'Hyderabad',  state: 'Telangana',   registeredYear: 2009, sector: 'Local & Home Services', subSector: 'Corporate housekeeping & office cleaning',         category: 'Small',  employeeRange: '300–600', annualTurnover: '₹25–55 Cr' },
  { id: 'ls008', name: 'Tenovia Solutions Pvt. Ltd.',         city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2014, sector: 'Local & Home Services', subSector: 'E-commerce marketplace services & cataloguing',    category: 'Micro',  employeeRange: '50–120',  annualTurnover: '₹8–20 Cr' },

  // ── D2C & Consumer Brands ─────────────────────────────────────────────────
  { id: 'dtc001', name: 'The Moms Co. (MyMindfulMom)',     city: 'Delhi',      state: 'Delhi',       registeredYear: 2016, sector: 'D2C & Consumer Brands', subSector: 'Natural baby & maternity care D2C brand',          category: 'Small',  employeeRange: '200–400', annualTurnover: '₹100–200 Cr' },
  { id: 'dtc002', name: 'Plum Goodness (Pureplay Skin)',   city: 'Mumbai',     state: 'Maharashtra', registeredYear: 2014, sector: 'D2C & Consumer Brands', subSector: 'Vegan skincare & personal care D2C brand',         category: 'Small',  employeeRange: '200–400', annualTurnover: '₹150–300 Cr', clusterNote: 'One of top 5 D2C beauty brands in India' },
  { id: 'dtc003', name: 'Mamaearth (Honasa Consumer)',     city: 'Gurgaon',    state: 'Haryana',     registeredYear: 2016, sector: 'D2C & Consumer Brands', subSector: 'Natural personal care & baby care products',       category: 'Medium', employeeRange: '2000+',  annualTurnover: '₹1500+ Cr',   clusterNote: 'Listed company — first profitable D2C unicorn' },
  { id: 'dtc004', name: 'boAt Lifestyle (Imagine Marketing)', city: 'Delhi',   state: 'Delhi',       registeredYear: 2016, sector: 'D2C & Consumer Brands', subSector: 'Audio electronics & wearables D2C brand',          category: 'Medium', employeeRange: '500+',   annualTurnover: '₹3000+ Cr',   clusterNote: 'Largest audio wearables brand in India' },
  { id: 'dtc005', name: 'SUGAR Cosmetics',                  city: 'Mumbai',     state: 'Maharashtra', registeredYear: 2015, sector: 'D2C & Consumer Brands', subSector: 'Cosmetics & makeup D2C brand',                    category: 'Small',  employeeRange: '500–800', annualTurnover: '₹300–600 Cr' },
  { id: 'dtc006', name: 'Bewakoof Brands Pvt. Ltd.',        city: 'Mumbai',     state: 'Maharashtra', registeredYear: 2012, sector: 'D2C & Consumer Brands', subSector: 'Youth fashion & casual wear D2C brand',            category: 'Small',  employeeRange: '500–800', annualTurnover: '₹200–400 Cr' },
  { id: 'dtc007', name: 'WakeFit Solutions',                 city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2016, sector: 'D2C & Consumer Brands', subSector: 'Mattresses, furniture & sleep products D2C',       category: 'Small',  employeeRange: '1500+',  annualTurnover: '₹600–1000 Cr' },
  { id: 'dtc008', name: 'Noise (GoQii Technologies)',        city: 'Gurgaon',    state: 'Haryana',     registeredYear: 2014, sector: 'D2C & Consumer Brands', subSector: 'Smartwatches & wearables D2C brand',               category: 'Small',  employeeRange: '300–600', annualTurnover: '₹500–800 Cr' },
  { id: 'dtc009', name: 'Licious (Delightful Gourmet)',      city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2015, sector: 'D2C & Consumer Brands', subSector: 'Fresh meat & seafood D2C delivery brand',          category: 'Medium', employeeRange: '3000+',  annualTurnover: '₹600–1000 Cr' },
  { id: 'dtc010', name: 'Country Delight (Bharat AgriLife)', city: 'Gurgaon',   state: 'Haryana',     registeredYear: 2015, sector: 'D2C & Consumer Brands', subSector: 'Farm-to-home dairy & organic food delivery',       category: 'Small',  employeeRange: '2000+',  annualTurnover: '₹400–700 Cr' },

  // ── Clean Energy & Environment ────────────────────────────────────────────
  { id: 'ce001', name: 'Fourth Partner Energy',            city: 'Hyderabad',  state: 'Telangana',   registeredYear: 2010, sector: 'Clean Energy & Environment', subSector: 'Commercial & industrial rooftop solar (C&I)',  category: 'Medium', employeeRange: '500+',   annualTurnover: '₹400–700 Cr',  clusterNote: 'Largest C&I solar developer — 1GW+ installed' },
  { id: 'ce002', name: 'Amplus Solar (PLP Energy)',        city: 'Delhi',      state: 'Delhi',       registeredYear: 2014, sector: 'Clean Energy & Environment', subSector: 'Captive & open access solar for industry',    category: 'Medium', employeeRange: '1000+',  annualTurnover: '₹1000+ Cr' },
  { id: 'ce003', name: 'Cleanmax Solar',                   city: 'Mumbai',     state: 'Maharashtra', registeredYear: 2011, sector: 'Clean Energy & Environment', subSector: 'Commercial rooftop & open-access solar',       category: 'Medium', employeeRange: '500–800', annualTurnover: '₹500–800 Cr' },
  { id: 'ce004', name: 'Attero Recycling Pvt. Ltd.',       city: 'Noida',      state: 'Uttar Pradesh', registeredYear: 2008, sector: 'Clean Energy & Environment', subSector: 'E-waste recycling & lithium battery recycling', category: 'Small', employeeRange: '400–700', annualTurnover: '₹200–400 Cr',  clusterNote: 'Only company in India recycling both e-waste & Li-ion batteries' },
  { id: 'ce005', name: 'Kabadiwala Connect Pvt. Ltd.',     city: 'Indore',     state: 'Madhya Pradesh', registeredYear: 2015, sector: 'Clean Energy & Environment', subSector: 'Doorstep dry waste collection & recycling',  category: 'Micro',  employeeRange: '100–200', annualTurnover: '₹10–25 Cr' },
  { id: 'ce006', name: 'Recykal (Nepra Resource Mgmt.)',   city: 'Hyderabad',  state: 'Telangana',   registeredYear: 2016, sector: 'Clean Energy & Environment', subSector: 'Digital waste marketplace & EPR compliance',   category: 'Small',  employeeRange: '200–400', annualTurnover: '₹50–100 Cr' },
  { id: 'ce007', name: 'Ecozen Solutions',                  city: 'Pune',       state: 'Maharashtra', registeredYear: 2011, sector: 'Clean Energy & Environment', subSector: 'Solar-powered cold storage for agriculture',   category: 'Small',  employeeRange: '200–400', annualTurnover: '₹80–160 Cr' },
  { id: 'ce008', name: 'Oorjan Cleantech Pvt. Ltd.',        city: 'Mumbai',     state: 'Maharashtra', registeredYear: 2019, sector: 'Clean Energy & Environment', subSector: 'Rooftop solar financing & installation',       category: 'Micro',  employeeRange: '50–120',  annualTurnover: '₹10–30 Cr' },

  // ── Logistics & Supply Chain ──────────────────────────────────────────────
  { id: 'log001', name: 'Shiprocket (BigFoot Retail Solutions)', city: 'Delhi',     state: 'Delhi',       registeredYear: 2017, sector: 'Logistics & Supply Chain', subSector: 'E-commerce shipping aggregator for D2C brands', category: 'Medium', employeeRange: '1000+',  annualTurnover: '₹400–700 Cr',  clusterNote: '100,000+ sellers — largest D2C shipping platform' },
  { id: 'log002', name: 'Pickrr Technologies',               city: 'Delhi',      state: 'Delhi',       registeredYear: 2015, sector: 'Logistics & Supply Chain', subSector: 'Multi-carrier shipping SaaS for e-commerce',    category: 'Small',  employeeRange: '300–600', annualTurnover: '₹80–160 Cr' },
  { id: 'log003', name: 'Vamaship (Ketan Logistic)',         city: 'Mumbai',     state: 'Maharashtra', registeredYear: 2017, sector: 'Logistics & Supply Chain', subSector: 'Freight rate comparison & booking platform',    category: 'Micro',  employeeRange: '50–120',  annualTurnover: '₹10–30 Cr' },
  { id: 'log004', name: 'Locus Technologies',                city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2015, sector: 'Logistics & Supply Chain', subSector: 'Route optimization & fleet dispatch SaaS',      category: 'Small',  employeeRange: '300–600', annualTurnover: '₹60–130 Cr' },
  { id: 'log005', name: 'Rivigo Services Pvt. Ltd.',         city: 'Gurgaon',    state: 'Haryana',     registeredYear: 2014, sector: 'Logistics & Supply Chain', subSector: 'Full-truckload freight & relay trucking model',  category: 'Medium', employeeRange: '3000+',  annualTurnover: '₹500–1000 Cr', clusterNote: 'Pioneered relay trucking model in India' },
  { id: 'log006', name: 'Shadowfax Technologies',            city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2015, sector: 'Logistics & Supply Chain', subSector: 'Last-mile delivery for e-commerce & quick commerce', category: 'Small', employeeRange: '2000+', annualTurnover: '₹300–600 Cr' },
  { id: 'log007', name: 'ElasticRun',                        city: 'Pune',       state: 'Maharashtra', registeredYear: 2016, sector: 'Logistics & Supply Chain', subSector: 'Rural FMCG distribution & last-mile B2B delivery', category: 'Small',  employeeRange: '1000+',  annualTurnover: '₹500–1000 Cr', clusterNote: 'Penetrates 50,000+ villages — FMCG rural supply chain' },
  { id: 'log008', name: 'WareIQ (ClaritasOps)',              city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2019, sector: 'Logistics & Supply Chain', subSector: 'Distributed warehousing & fulfilment SaaS',      category: 'Micro',  employeeRange: '100–200', annualTurnover: '₹20–50 Cr' },

  // ── Real Estate Services ──────────────────────────────────────────────────
  { id: 're001', name: 'NoBroker Technologies',             city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2014, sector: 'Real Estate Services', subSector: 'Zero-brokerage property rental & sales platform',  category: 'Medium', employeeRange: '5000+',  annualTurnover: '₹600–1000 Cr', clusterNote: 'Largest Indian proptech unicorn — 9M+ listings' },
  { id: 're002', name: 'Square Yards (SY Technologies)',    city: 'Gurgaon',    state: 'Haryana',     registeredYear: 2014, sector: 'Real Estate Services', subSector: 'Real estate transactions & home loan platform',     category: 'Medium', employeeRange: '3000+',  annualTurnover: '₹400–800 Cr' },
  { id: 're003', name: 'PropTiger (REA India Pvt. Ltd.)',   city: 'Gurgaon',    state: 'Haryana',     registeredYear: 2011, sector: 'Real Estate Services', subSector: 'Primary real estate sales & developer marketing',   category: 'Medium', employeeRange: '3000+',  annualTurnover: '₹300–600 Cr', clusterNote: 'Part of REA Group (Australia) — also owns Housing.com' },
  { id: 're004', name: 'Magicbricks (Times Internet)',      city: 'Noida',      state: 'Uttar Pradesh', registeredYear: 2006, sector: 'Real Estate Services', subSector: 'Property listings portal — rent, buy & commercial', category: 'Medium', employeeRange: '1000+',  annualTurnover: '₹300–500 Cr' },
  { id: 're005', name: 'Stanza Living (Dtwelve Spaces)',    city: 'Delhi',      state: 'Delhi',       registeredYear: 2017, sector: 'Real Estate Services', subSector: 'Managed student & young professional accommodations', category: 'Small',  employeeRange: '1500+',  annualTurnover: '₹200–400 Cr' },
  { id: 're006', name: 'Nestaway Technologies',             city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2015, sector: 'Real Estate Services', subSector: 'Managed rental homes & co-living management',       category: 'Small',  employeeRange: '500–800', annualTurnover: '₹60–130 Cr' },
  { id: 're007', name: 'Colive (Tricho Technologies)',      city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2016, sector: 'Real Estate Services', subSector: 'Premium co-living spaces for working professionals', category: 'Small',  employeeRange: '300–600', annualTurnover: '₹50–100 Cr' },

  // ── Travel & Hospitality ──────────────────────────────────────────────────
  { id: 'tr001', name: 'OYO Rooms (Oravel Stays)',          city: 'Gurgaon',    state: 'Haryana',     registeredYear: 2013, sector: 'Travel & Hospitality', subSector: 'Budget hotel aggregation & property management',   category: 'Medium', employeeRange: '10000+', annualTurnover: '₹5000+ Cr',  clusterNote: 'Largest hospitality chain by rooms — 157,000+ hotels globally' },
  { id: 'tr002', name: 'FabHotels (Acacia Hotels)',         city: 'Delhi',      state: 'Delhi',       registeredYear: 2014, sector: 'Travel & Hospitality', subSector: 'Standardised budget hotel brand & management',     category: 'Small',  employeeRange: '1000+',  annualTurnover: '₹200–400 Cr' },
  { id: 'tr003', name: 'Zostel (ZoStay Hospitality)',       city: 'Delhi',      state: 'Delhi',       registeredYear: 2013, sector: 'Travel & Hospitality', subSector: 'Backpacker hostels & social travel network',       category: 'Small',  employeeRange: '500–800', annualTurnover: '₹50–100 Cr',  clusterNote: 'Largest hostel chain in South Asia — 200+ properties' },
  { id: 'tr004', name: 'Thomas Cook India Ltd.',            city: 'Mumbai',     state: 'Maharashtra', registeredYear: 1881, sector: 'Travel & Hospitality', subSector: 'Outbound travel, MICE & corporate travel management', category: 'Medium', employeeRange: '3000+', annualTurnover: '₹1500+ Cr' },
  { id: 'tr005', name: 'Kesari Tours Pvt. Ltd.',            city: 'Mumbai',     state: 'Maharashtra', registeredYear: 1984, sector: 'Travel & Hospitality', subSector: 'Domestic & international tour packages',           category: 'Small',  employeeRange: '1000+',  annualTurnover: '₹300–600 Cr', clusterNote: 'Maharashtra\'s largest tour operator — 70+ years' },
  { id: 'tr006', name: 'Thrillophilia (OT Adventures)',     city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2009, sector: 'Travel & Hospitality', subSector: 'Adventure & experiential travel marketplace',      category: 'Small',  employeeRange: '200–400', annualTurnover: '₹50–100 Cr' },
  { id: 'tr007', name: 'Treebo Hotels (Treebo Tech)',        city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2015, sector: 'Travel & Hospitality', subSector: 'Tech-enabled budget hotel brand management',       category: 'Small',  employeeRange: '500–800', annualTurnover: '₹100–200 Cr' },
  { id: 'tr008', name: 'Via.com (Flightraja Travels)',      city: 'Chennai',    state: 'Tamil Nadu',  registeredYear: 2006, sector: 'Travel & Hospitality', subSector: 'B2B travel distribution & agent booking platform',  category: 'Small',  employeeRange: '500–800', annualTurnover: '₹100–200 Cr' },

  // ── Pet Care & Veterinary ─────────────────────────────────────────────────
  { id: 'pet001', name: 'Heads Up For Tails (HUFT)',        city: 'Delhi',      state: 'Delhi',       registeredYear: 2008, sector: 'Pet Care & Veterinary', subSector: 'Premium pet food, accessories & grooming retail', category: 'Small',  employeeRange: '500–800', annualTurnover: '₹150–300 Cr',  clusterNote: '100+ stores & strong online presence — premium positioning' },
  { id: 'pet002', name: 'Wiggles (OneCare Bioscience)',     city: 'Mumbai',     state: 'Maharashtra', registeredYear: 2020, sector: 'Pet Care & Veterinary', subSector: 'Pet healthcare products & supplements D2C',       category: 'Micro',  employeeRange: '50–120',  annualTurnover: '₹10–30 Cr' },
  { id: 'pet003', name: 'Drools (Cannis Lupus Foods)',       city: 'Delhi',      state: 'Delhi',       registeredYear: 2013, sector: 'Pet Care & Veterinary', subSector: 'Affordable dry & wet pet food for dogs & cats',   category: 'Small',  employeeRange: '200–400', annualTurnover: '₹150–300 Cr',  clusterNote: 'Fastest growing value pet food brand — 40,000+ retail points' },
  { id: 'pet004', name: 'PetSutra (Sutra Infotech)',        city: 'Delhi',      state: 'Delhi',       registeredYear: 2012, sector: 'Pet Care & Veterinary', subSector: 'Online pet supplies, food & accessories marketplace', category: 'Micro', employeeRange: '50–100',  annualTurnover: '₹10–25 Cr' },
  { id: 'pet005', name: 'Supertails (Phodun Petcare)',       city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2021, sector: 'Pet Care & Veterinary', subSector: 'D2C pet food, health & telehealth for pets',       category: 'Micro',  employeeRange: '100–200', annualTurnover: '₹20–50 Cr' },
  { id: 'pet006', name: 'Dogspot (Freshway Foods)',          city: 'Delhi',      state: 'Delhi',       registeredYear: 2008, sector: 'Pet Care & Veterinary', subSector: 'Pet e-commerce & community platform',             category: 'Micro',  employeeRange: '50–100',  annualTurnover: '₹8–20 Cr' },

  // ── Export & Trade Services ───────────────────────────────────────────────
  { id: 'exp001', name: 'Exporters India (MAIT Info Systems)', city: 'Delhi',   state: 'Delhi',       registeredYear: 1997, sector: 'Export & Trade Services', subSector: 'B2B trade portal connecting exporters with global buyers', category: 'Small', employeeRange: '300–600', annualTurnover: '₹50–100 Cr' },
  { id: 'exp002', name: 'Maersk India Pvt. Ltd.',             city: 'Mumbai',    state: 'Maharashtra', registeredYear: 1990, sector: 'Export & Trade Services', subSector: 'Ocean freight, container shipping & logistics',   category: 'Medium', employeeRange: '1000+',  annualTurnover: '₹2000+ Cr',   clusterNote: 'Maersk Group (Denmark) India entity — largest ocean carrier' },
  { id: 'exp003', name: 'Cogoport (Cogo Freight)',            city: 'Mumbai',    state: 'Maharashtra', registeredYear: 2017, sector: 'Export & Trade Services', subSector: 'Digital freight forwarding & customs clearance', category: 'Small',  employeeRange: '300–600', annualTurnover: '₹80–160 Cr' },
  { id: 'exp004', name: 'Drip Capital',                       city: 'Mumbai',    state: 'Maharashtra', registeredYear: 2015, sector: 'Export & Trade Services', subSector: 'Trade finance & invoice discounting for exporters', category: 'Small', employeeRange: '200–400', annualTurnover: '₹100–200 Cr', clusterNote: 'Finances SME exporters — $1B+ disbursements' },
  { id: 'exp005', name: 'Bizongo (earlier listed)',            city: 'Mumbai',    state: 'Maharashtra', registeredYear: 2015, sector: 'Export & Trade Services', subSector: 'B2B packaging procurement & supply chain',       category: 'Medium', employeeRange: '500+',   annualTurnover: '₹500–1000 Cr' },
  { id: 'exp006', name: 'Arya.ag (Arya Collateral Warehousing)', city: 'Delhi', state: 'Delhi',       registeredYear: 2012, sector: 'Export & Trade Services', subSector: 'Commodity warehousing, collateral & trade finance', category: 'Small', employeeRange: '400–700', annualTurnover: '₹100–200 Cr',  clusterNote: '700+ warehouses — grain storage & commodity trade finance' },

  // ── Food & Beverage ───────────────────────────────────────────────────────
  { id: 'fb001', name: 'ITC Foods Division',               city: 'Kolkata',    state: 'West Bengal', registeredYear: 1910, sector: 'Food & Beverage', subSector: 'Branded foods — Aashirvad, Sunfeast, Bingo',       category: 'Medium', employeeRange: '20000+', annualTurnover: '₹15000+ Cr',  clusterNote: 'ITC Ltd. foods vertical — distribution in every PIN code' },
  { id: 'fb002', name: 'Haldiram\'s Snacks Food Pvt. Ltd.', city: 'Delhi',     state: 'Delhi',       registeredYear: 1937, sector: 'Food & Beverage', subSector: 'Namkeen, sweets, snacks & restaurants',           category: 'Medium', employeeRange: '10000+', annualTurnover: '₹8000+ Cr',   clusterNote: 'India\'s largest snack brand — 60+ countries' },
  { id: 'fb003', name: 'Amul (GCMMF)',                      city: 'Anand',      state: 'Gujarat',     registeredYear: 1946, sector: 'Food & Beverage', subSector: 'Dairy — milk, butter, cheese, ice cream',         category: 'Medium', employeeRange: '5000+',  annualTurnover: '₹55000+ Cr',  clusterNote: 'World\'s largest dairy cooperative — pan-India cold chain' },
  { id: 'fb004', name: 'Wow! Momo Foods Pvt. Ltd.',         city: 'Kolkata',    state: 'West Bengal', registeredYear: 2008, sector: 'Food & Beverage', subSector: 'Quick service restaurant — momos & Chinese food',   category: 'Small',  employeeRange: '5000+',  annualTurnover: '₹500–800 Cr' },
  { id: 'fb005', name: 'Speciality Foods India (iD Fresh)', city: 'Bengaluru',  state: 'Karnataka',   registeredYear: 2005, sector: 'Food & Beverage', subSector: 'Ready-to-cook South Indian foods (idly, dosa batter)', category: 'Small', employeeRange: '2000+', annualTurnover: '₹400–700 Cr',  clusterNote: 'Present in UAE, US & Middle East — ₹1000 Cr target' },
  { id: 'fb006', name: 'Veeba Food Services',               city: 'Noida',      state: 'Uttar Pradesh', registeredYear: 2013, sector: 'Food & Beverage', subSector: 'Sauces, dressings & condiments B2B & D2C',    category: 'Small',  employeeRange: '500–800', annualTurnover: '₹200–400 Cr' },
  { id: 'fb007', name: 'Epigamia (Drums Food International)', city: 'Mumbai',   state: 'Maharashtra', registeredYear: 2015, sector: 'Food & Beverage', subSector: 'Greek yogurt, smoothies & functional dairy D2C',    category: 'Small',  employeeRange: '300–600', annualTurnover: '₹150–300 Cr' },
  { id: 'fb008', name: 'Just Herbs (Lotus Herbals Group)',   city: 'Delhi',      state: 'Delhi',       registeredYear: 2015, sector: 'Food & Beverage', subSector: 'Ayurvedic food supplements & herbal products D2C', category: 'Micro',  employeeRange: '100–200', annualTurnover: '₹20–50 Cr' },

  // ── Plastics & Rubber ─────────────────────────────────────────────────────
  { id: 'pr001', name: 'Rajkot Rubber Works',          city: 'Rajkot',     state: 'Gujarat',     registeredYear: 1996, sector: 'Plastics & Rubber', subSector: 'Moulded rubber products & anti-vibration mounts', category: 'Small',  employeeRange: '30–65',  annualTurnover: '₹3.5–8 Cr',  clusterNote: 'Rajkot rubber processing belt' },
  { id: 'pr002', name: 'Ambica Rubber Extrusions',     city: 'Vadodara',   state: 'Gujarat',     registeredYear: 2007, sector: 'Plastics & Rubber', subSector: 'Rubber profiles, gaskets & seals',              category: 'Small',  employeeRange: '25–55',  annualTurnover: '₹2.5–6 Cr' },
  { id: 'pr005', name: 'Siddhi Vinayak Polymers',      city: 'Pune',       state: 'Maharashtra', registeredYear: 2014, sector: 'Plastics & Rubber', subSector: 'Polyurethane castors, wheels & bushes',         category: 'Small',  employeeRange: '18–40',  annualTurnover: '₹1.8–4 Cr' },
  { id: 'pr006', name: 'Perfect Castor Wheel Works',   city: 'Mumbai',     state: 'Maharashtra', registeredYear: 2003, sector: 'Plastics & Rubber', subSector: 'Industrial castor wheels & trolley wheels',     category: 'Small',  employeeRange: '22–48',  annualTurnover: '₹2.5–5.5 Cr' },
  { id: 'pr004', name: 'Coimbatore Rubber Industries', city: 'Coimbatore', state: 'Tamil Nadu',  registeredYear: 2000, sector: 'Plastics & Rubber', subSector: 'Industrial rubber rollers & cots',              category: 'Small',  employeeRange: '35–70',  annualTurnover: '₹4–9 Cr',    clusterNote: 'Coimbatore textile machinery cluster' },

  // ── Metal & Engineering ───────────────────────────────────────────────────
  { id: 'm001', name: 'Ludhiana Fastener Industries', city: 'Ludhiana',   state: 'Punjab',      registeredYear: 1994, sector: 'Metal & Engineering', subSector: 'Fasteners, bolts & industrial hardware',  category: 'Small',  employeeRange: '35–75',  annualTurnover: '₹4–9 Cr',    clusterNote: 'Ludhiana fastener cluster — 2000+ units' },
  { id: 'm002', name: 'Rajkot Engineering Works',     city: 'Rajkot',     state: 'Gujarat',     registeredYear: 1989, sector: 'Metal & Engineering', subSector: 'Precision machined components & castings', category: 'Medium', employeeRange: '60–120', annualTurnover: '₹8–18 Cr',   clusterNote: 'Rajkot engineering cluster' },
  { id: 'm003', name: 'Kolhapur Metal Stampings',     city: 'Kolhapur',   state: 'Maharashtra', registeredYear: 2001, sector: 'Metal & Engineering', subSector: 'Metal stampings & pressed components',     category: 'Small',  employeeRange: '30–65',  annualTurnover: '₹3.5–8 Cr',  clusterNote: 'Kolhapur foundry cluster' },
  { id: 'm006', name: 'Coimbatore CNC Machining',     city: 'Coimbatore', state: 'Tamil Nadu',  registeredYear: 2011, sector: 'Metal & Engineering', subSector: 'CNC turned parts & machined components',   category: 'Small',  employeeRange: '22–50',  annualTurnover: '₹2.5–6 Cr',  clusterNote: 'Coimbatore engineering cluster' },
  { id: 'm008', name: 'Vatva Industrial Forgings',    city: 'Ahmedabad',  state: 'Gujarat',     registeredYear: 1999, sector: 'Metal & Engineering', subSector: 'Ferrous & non-ferrous forgings',           category: 'Medium', employeeRange: '50–100', annualTurnover: '₹7–16 Cr',   clusterNote: 'Vatva GIDC industrial estate' },

  // ── Industrial Services ───────────────────────────────────────────────────
  { id: 'svc001', name: 'Spectrum Calibration Services', city: 'Pune',      state: 'Maharashtra', registeredYear: 2007, sector: 'Industrial Services', subSector: 'NABL calibration — instruments & gauges',       category: 'Small', employeeRange: '15–35', annualTurnover: '₹1.5–4 Cr',  clusterNote: 'NABL accredited, serving auto & pharma clusters' },
  { id: 'svc002', name: 'Precise Metrology Lab',         city: 'Chennai',   state: 'Tamil Nadu',  registeredYear: 2010, sector: 'Industrial Services', subSector: 'Dimensional & electrical calibration',          category: 'Small', employeeRange: '12–28', annualTurnover: '₹1–2.5 Cr' },
  { id: 'svc003', name: 'Vertical Access Solutions',     city: 'Mumbai',    state: 'Maharashtra', registeredYear: 2012, sector: 'Industrial Services', subSector: 'Rope access facade & industrial inspection',     category: 'Small', employeeRange: '18–40', annualTurnover: '₹1.5–4 Cr',  clusterNote: 'IRATA certified team' },
  { id: 'svc004', name: 'Energy Efficiency Consultants', city: 'Bengaluru', state: 'Karnataka',   registeredYear: 2009, sector: 'Industrial Services', subSector: 'Compressed air audits & energy leak detection',  category: 'Micro', employeeRange: '8–20',  annualTurnover: '₹40–120 L' },
  { id: 'svc005', name: 'Infraview Thermal Imaging',     city: 'Pune',      state: 'Maharashtra', registeredYear: 2015, sector: 'Industrial Services', subSector: 'Thermographic inspection — electrical & solar',  category: 'Micro', employeeRange: '6–15',  annualTurnover: '₹30–90 L' },
  { id: 'svc006', name: 'Southern NDT Services',         city: 'Chennai',   state: 'Tamil Nadu',  registeredYear: 2004, sector: 'Industrial Services', subSector: 'Non-destructive testing (UT, RT, PT, MT)',       category: 'Small', employeeRange: '20–45', annualTurnover: '₹2–4.5 Cr' },

  // ── Electronics & Electrical ──────────────────────────────────────────────
  { id: 'e001', name: 'Omkar Control Systems',    city: 'Pune',      state: 'Maharashtra', registeredYear: 2008, sector: 'Electronics & Electrical', subSector: 'Industrial control panels & automation', category: 'Small',  employeeRange: '20–45',  annualTurnover: '₹2.5–6 Cr' },
  { id: 'e003', name: 'Gujarat Transformer Works', city: 'Vadodara', state: 'Gujarat',     registeredYear: 2001, sector: 'Electronics & Electrical', subSector: 'Distribution transformers & dry-type units', category: 'Medium', employeeRange: '55–110', annualTurnover: '₹7–16 Cr' },
  { id: 'e004', name: 'Perfect Switch Gear',       city: 'Mumbai',    state: 'Maharashtra', registeredYear: 2005, sector: 'Electronics & Electrical', subSector: 'Switchboards & LT panels',               category: 'Small',  employeeRange: '25–55',  annualTurnover: '₹3–7 Cr' },
  { id: 'e005', name: 'Shivam Electronics',        city: 'Bengaluru', state: 'Karnataka',   registeredYear: 2016, sector: 'Electronics & Electrical', subSector: 'PCB assembly & electronic subassemblies', category: 'Micro',  employeeRange: '12–28',  annualTurnover: '₹70–180 L' },

  // ── Textile & Apparel ─────────────────────────────────────────────────────
  { id: 't001', name: 'Tiruppur Knit Wear Mfg.',  city: 'Tiruppur', state: 'Tamil Nadu',  registeredYear: 1999, sector: 'Textile & Apparel', subSector: 'Knitwear, T-shirts & hosiery for export',     category: 'Small',  employeeRange: '50–110', annualTurnover: '₹6–14 Cr',   clusterNote: 'Tiruppur knitwear cluster' },
  { id: 't002', name: 'Surat Synthetic Fabrics',  city: 'Surat',    state: 'Gujarat',     registeredYear: 2002, sector: 'Textile & Apparel', subSector: 'Synthetic fabrics, sarees & dress materials', category: 'Small',  employeeRange: '30–70',  annualTurnover: '₹4–9 Cr',    clusterNote: 'Surat textile cluster' },
  { id: 't003', name: 'Ludhiana Woollen Mills',   city: 'Ludhiana', state: 'Punjab',      registeredYear: 1990, sector: 'Textile & Apparel', subSector: 'Woollen yarn, blankets & knitwear',           category: 'Medium', employeeRange: '65–130', annualTurnover: '₹9–20 Cr',   clusterNote: 'Ludhiana wool cluster' },
  { id: 't004', name: 'Kolhapur Safety Workwear', city: 'Kolhapur', state: 'Maharashtra', registeredYear: 2008, sector: 'Textile & Apparel', subSector: 'Industrial uniforms & safety workwear',       category: 'Small',  employeeRange: '25–55',  annualTurnover: '₹2.5–6 Cr' },

  // ── Food Processing (manufacturing-side) ──────────────────────────────────
  { id: 'f001', name: 'Maharashtra Food Tech',         city: 'Nashik',     state: 'Maharashtra', registeredYear: 2009, sector: 'Food Processing', subSector: 'Fruit & vegetable processing & IQF',         category: 'Small', employeeRange: '30–65', annualTurnover: '₹4–9 Cr' },
  { id: 'f002', name: 'Gujarat Agro Industries',       city: 'Rajkot',     state: 'Gujarat',     registeredYear: 2003, sector: 'Food Processing', subSector: 'Groundnut oil cold press & processing',       category: 'Small', employeeRange: '20–45', annualTurnover: '₹3–7 Cr' },
  { id: 'f003', name: 'South India Spice Exports',     city: 'Coimbatore', state: 'Tamil Nadu',  registeredYear: 1998, sector: 'Food Processing', subSector: 'Spice grinding, blending & export',           category: 'Small', employeeRange: '35–70', annualTurnover: '₹5–12 Cr' },
  { id: 'f005', name: 'Amruth Dairy Products',         city: 'Hyderabad',  state: 'Telangana',   registeredYear: 2006, sector: 'Food Processing', subSector: 'Dairy processing & value-added dairy',        category: 'Small', employeeRange: '25–55', annualTurnover: '₹3–7 Cr' },

  // ── Paper & Print ─────────────────────────────────────────────────────────
  { id: 'pp001', name: 'Star Paper Tubes & Cores',  city: 'Ahmedabad', state: 'Gujarat',     registeredYear: 2007, sector: 'Paper & Print', subSector: 'Paper cores, tubes & bobbins for textile/film', category: 'Small', employeeRange: '20–45', annualTurnover: '₹2–5 Cr' },
  { id: 'pp002', name: 'Associated Print Works',    city: 'Delhi',     state: 'Delhi',       registeredYear: 2000, sector: 'Paper & Print', subSector: 'Flexible packaging printing & converting',     category: 'Small', employeeRange: '28–60', annualTurnover: '₹3–7 Cr' },
  { id: 'pp003', name: 'Coimbatore Offset Printers', city: 'Coimbatore', state: 'Tamil Nadu', registeredYear: 2005, sector: 'Paper & Print', subSector: 'Commercial offset printing & label printing',  category: 'Small', employeeRange: '18–40', annualTurnover: '₹2–4.5 Cr' },
]
