export type IncentiveType =
  | 'capital-subsidy'
  | 'interest-subsidy'
  | 'stamp-duty'
  | 'electricity'
  | 'gst-reimbursement'
  | 'employment'
  | 'tax-holiday'
  | 'other'

export type EnterpriseSizeKey = 'micro' | 'small' | 'medium' | 'large'
export type SectorKey = 'all' | 'manufacturing' | 'food' | 'technology' | 'textile' | 'agriculture' | 'services' | 'energy'

export interface Incentive {
  id: string
  state: string
  name: string
  type: IncentiveType
  sectors: SectorKey[]
  amount: string           // human-readable highlight
  eligibility: string
  duration: string
  enterpriseSize: EnterpriseSizeKey[]
  newOnly: boolean
  forWomen: boolean
  forScSt: boolean
  policyName: string
  sourceUrl: string
}

export const INCENTIVES: Incentive[] = [
  // ── MAHARASHTRA ───────────────────────────────────────────────────────────
  {
    id: 'mh-1', state: 'Maharashtra',
    name: 'Industrial Promotion Subsidy — Zone C',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '40% of FCI as 100% Gross SGST reimbursement',
    eligibility: 'New/expansion MSMEs in Zone C (semi-developed) districts',
    duration: '7 years from commercial production',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Package Scheme of Incentives (PSI) 2019',
    sourceUrl: 'https://doingbusinessinmaharashtra.org/Incentives.php',
  },
  {
    id: 'mh-2', state: 'Maharashtra',
    name: 'Industrial Promotion Subsidy — Vidarbha / Marathwada',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '80% of FCI as 100% Gross SGST reimbursement',
    eligibility: 'New MSMEs in Vidarbha, Marathwada, North Maharashtra, Aspirational Districts',
    duration: '10 years from commercial production',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Package Scheme of Incentives (PSI) 2019',
    sourceUrl: 'https://doingbusinessinmaharashtra.org/Incentives.php',
  },
  {
    id: 'mh-3', state: 'Maharashtra',
    name: 'Stamp Duty Exemption',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: '100% waiver in C, D, D+ and No-Industry Districts; 75% for private IT parks in A/B zones',
    eligibility: 'New/expansion units buying or leasing industrial land',
    duration: 'One-time at registration',
    enterpriseSize: ['micro', 'small', 'medium', 'large'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Package Scheme of Incentives (PSI) 2019',
    sourceUrl: 'https://doingbusinessinmaharashtra.org/Incentives.php',
  },
  {
    id: 'mh-4', state: 'Maharashtra',
    name: 'Power Tariff Subsidy',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '₹1/unit in Vidarbha, Marathwada, North Maharashtra; ₹0.50/unit elsewhere',
    eligibility: 'New eligible industrial units in qualifying regions',
    duration: '3 years from commercial production',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Package Scheme of Incentives (PSI) 2019',
    sourceUrl: 'https://doingbusinessinmaharashtra.org/Incentives.php',
  },
  {
    id: 'mh-5', state: 'Maharashtra',
    name: 'Technology Upgradation Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '5% on capital equipment, max ₹25 lakhs',
    eligibility: 'Micro and small enterprises upgrading to new technology',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small'], newOnly: false, forWomen: false, forScSt: false,
    policyName: 'Maharashtra MSME Schemes 2023',
    sourceUrl: 'https://mahasdb.maharashtra.gov.in/files/DSP/Sector/MSMEschemes_8thAugust2023.pdf',
  },

  // ── GUJARAT ───────────────────────────────────────────────────────────────
  {
    id: 'gj-1', state: 'Gujarat',
    name: 'Capital Investment Subsidy — Category I Talukas',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '25% of eligible term loan, max ₹35 lakhs (+₹10L if FCI > ₹10 cr)',
    eligibility: 'New/expansion MSME manufacturing in most-backward Category I talukas',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Gujarat Industrial Policy 2020',
    sourceUrl: 'https://www.investindia.gov.in/team-india-blogs/understanding-gujarat-industrial-policy-2020-part-34-subsidies-and-incentives',
  },
  {
    id: 'gj-2', state: 'Gujarat',
    name: 'Capital Investment Subsidy — Category II Talukas',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '20% of eligible term loan, max ₹30 lakhs',
    eligibility: 'New/expansion MSME manufacturing in developing Category II talukas',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Gujarat Industrial Policy 2020',
    sourceUrl: 'https://www.investindia.gov.in/team-india-blogs/understanding-gujarat-industrial-policy-2020-part-34-subsidies-and-incentives',
  },
  {
    id: 'gj-3', state: 'Gujarat',
    name: 'Interest Subsidy — Category I',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '7% p.a. on term loan, max ₹35 lakh/year',
    eligibility: 'New/expansion MSME in Category I backward talukas',
    duration: '7 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Gujarat Industrial Policy 2020',
    sourceUrl: 'https://adroitcorporation.in/interest-subsidy-under-industrial-policy-2020-to-msmes-in-gujarat/',
  },
  {
    id: 'gj-4', state: 'Gujarat',
    name: 'Additional 1% Interest Subsidy — Women / SC-ST / Youth',
    type: 'interest-subsidy', sectors: ['all'],
    amount: 'Additional 1% over category rate (minimum 2% residual borne by unit)',
    eligibility: 'Women, SC/ST, differently-abled, startup entrepreneurs, or under 35 years',
    duration: 'Same as category duration',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'Gujarat Industrial Policy 2020',
    sourceUrl: 'https://www.investindia.gov.in/team-india-blogs/understanding-gujarat-industrial-policy-2020-part-34-subsidies-and-incentives',
  },
  {
    id: 'gj-5', state: 'Gujarat',
    name: 'ZED Quality Certification Support',
    type: 'other', sectors: ['manufacturing'],
    amount: '50% of certification charges, max ₹50,000',
    eligibility: 'All registered MSMEs obtaining ZED or quality certification',
    duration: 'Per certification',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: false, forWomen: false, forScSt: false,
    policyName: 'Gujarat Industrial Policy 2020',
    sourceUrl: 'https://thesubsidysquad.com/scheme-for-assistance-to-msme-under-gujarat-industrial-policy-2020/',
  },

  // ── KARNATAKA ─────────────────────────────────────────────────────────────
  {
    id: 'ka-1', state: 'Karnataka',
    name: 'Capital Subsidy — Zone 1 (Micro Enterprises)',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '30% of Value of Fixed Assets (VFA), max ₹30 lakhs',
    eligibility: 'New micro enterprises in most-backward Zone 1 talukas',
    duration: 'One-time',
    enterpriseSize: ['micro'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Karnataka Industrial Policy 2025-30',
    sourceUrl: 'https://goleassociates.com/unlocking-growth-comprehensive-guide-to-msme-subsidies-in-karnataka-under-the-industrial-policy-2025-30',
  },
  {
    id: 'ka-2', state: 'Karnataka',
    name: 'Capital Subsidy — Zone 1 (Small & Medium)',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '20% of VFA, max ₹1 crore',
    eligibility: 'New small/medium enterprises in Zone 1 talukas',
    duration: 'One-time',
    enterpriseSize: ['small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Karnataka Industrial Policy 2025-30',
    sourceUrl: 'https://goleassociates.com/unlocking-growth-comprehensive-guide-to-msme-subsidies-in-karnataka-under-the-industrial-policy-2025-30',
  },
  {
    id: 'ka-3', state: 'Karnataka',
    name: 'SC/ST / Women Enhanced Capital Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '35% of VFA (Zone 1), 30% (Zone 2), 15% (Zone 3)',
    eligibility: 'SC/ST, women, and differently-abled entrepreneurs',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'Karnataka Industrial Policy 2025-30',
    sourceUrl: 'https://ibcworldnews.com/2026/03/27/karnataka-unveils-industrial-policy-2025-30-with-boost-for-sc-st-entrepreneurs/',
  },
  {
    id: 'ka-4', state: 'Karnataka',
    name: 'Electricity Tax Exemption',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '100% exemption on electricity/power tariff tax',
    eligibility: 'All new MSME manufacturing units (Zone 1: 7 yrs, Zone 2: 6 yrs, Zone 3: 5 yrs)',
    duration: '5–7 years from commercial production',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Karnataka Industrial Policy 2025-30',
    sourceUrl: 'https://www.india-briefing.com/news/karnatakas-new-industrial-policy-for-2020-25-what-should-india-bound-foreign-investors-expect-20649.html/',
  },
  {
    id: 'ka-5', state: 'Karnataka',
    name: 'Stamp Duty Exemption',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: '100% exemption on stamp duty and concessional registration charges',
    eligibility: 'All MSMEs in Zone 1 and Zone 2 (Zone 3 excluded)',
    duration: 'One-time at registration',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Karnataka Industrial Policy 2025-30',
    sourceUrl: 'https://goleassociates.com/unlocking-growth-comprehensive-guide-to-msme-subsidies-in-karnataka-under-the-industrial-policy-2025-30',
  },

  // ── TAMIL NADU ────────────────────────────────────────────────────────────
  {
    id: 'tn-1', state: 'Tamil Nadu',
    name: 'Capital Subsidy for MSMEs',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '25% of eligible plant & machinery value, max ₹150 lakhs',
    eligibility: 'New/expansion MSMEs in general districts',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Tamil Nadu Industrial Policy 2021',
    sourceUrl: 'https://taxguru.in/corporate-law/tamil-nadu-industrial-policy-2021.html',
  },
  {
    id: 'tn-2', state: 'Tamil Nadu',
    name: 'SGST Reimbursement',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '100% SGST reimbursement on sales within Tamil Nadu',
    eligibility: 'MSMEs manufacturing goods sold within Tamil Nadu',
    duration: '15 years from commercial production',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Tamil Nadu Industrial Policy 2021',
    sourceUrl: 'https://interlinkcapital.in/tamilnadu-state-industrial-policy.php',
  },
  {
    id: 'tn-3', state: 'Tamil Nadu',
    name: 'Stamp Duty Concession',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: '100% exemption for micro enterprises; 50% for small enterprises; 100% in SIPCOT parks',
    eligibility: 'New/expansion micro and small units mortgaging/purchasing industrial assets',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Tamil Nadu Industrial Policy 2021',
    sourceUrl: 'https://www.mondaq.com/india/corporate-and-company-law/1347060/incentives-for-new-manufacturing-set-ups-tamil-nadu',
  },
  {
    id: 'tn-4', state: 'Tamil Nadu',
    name: 'Electricity Tax Exemption',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '100% electricity tax exemption (power purchased from TANGEDCO)',
    eligibility: 'All MSME manufacturing units',
    duration: '5 years from commercial production',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Tamil Nadu Industrial Policy 2021',
    sourceUrl: 'https://interlinkcapital.in/tamilnadu-state-industrial-policy.php',
  },
  {
    id: 'tn-5', state: 'Tamil Nadu',
    name: 'Employment Training Subsidy — Women/SC-ST',
    type: 'employment', sectors: ['manufacturing'],
    amount: '₹6,000/worker/month for 6 months (vs ₹4,000 for general category)',
    eligibility: 'Women or SC/ST entrepreneurs hiring new workers',
    duration: '6 months per eligible hire',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: false, forWomen: true, forScSt: true,
    policyName: 'Tamil Nadu Industrial Policy 2021',
    sourceUrl: 'https://interlinkcapital.in/tamilnadu-state-industrial-policy.php',
  },

  // ── TELANGANA ─────────────────────────────────────────────────────────────
  {
    id: 'tg-1', state: 'Telangana',
    name: 'Capital Investment Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '25% on fixed capital (land, building, plant & machinery), max ₹30 lakhs',
    eligibility: 'New MSME manufacturing units',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Telangana MSME Promotion Policy 2024',
    sourceUrl: 'https://kipfinancial.com/telangana-state-specific-subsidy-benefits-for-msme-units/',
  },
  {
    id: 'tg-2', state: 'Telangana',
    name: 'Women Entrepreneur Additional Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: 'Additional 20% subsidy, up to ₹10 lakhs extra over standard rate',
    eligibility: 'Women-owned enterprises (51%+ ownership by women)',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: true, forScSt: false,
    policyName: 'Telangana MSME Promotion Policy 2024',
    sourceUrl: 'https://kipfinancial.com/telangana-state-specific-subsidy-benefits-for-msme-units/',
  },
  {
    id: 'tg-3', state: 'Telangana',
    name: 'T-PRIDE Scheme for SC/ST',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '35%–50% investment subsidy, max ₹75 lakh–₹1 crore; 100% tax reimbursement for 5 years',
    eligibility: 'SC/ST entrepreneurs starting new manufacturing units',
    duration: 'Per T-PRIDE scheme terms',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: true,
    policyName: 'T-PRIDE Scheme',
    sourceUrl: 'https://startupflora.com/post/telangana-government-schemes-for-startups-and-msmes-2025',
  },
  {
    id: 'tg-4', state: 'Telangana',
    name: 'SGST Reimbursement',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '100% SGST reimbursement',
    eligibility: 'All eligible MSME manufacturing units',
    duration: '5 years from commercial production',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Telangana MSME Promotion Policy 2024',
    sourceUrl: 'https://kipfinancial.com/telangana-state-specific-subsidy-benefits-for-msme-units/',
  },
  {
    id: 'tg-5', state: 'Telangana',
    name: 'Power Tariff Subsidy',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '₹1/unit reimbursement',
    eligibility: 'All eligible MSME manufacturing units',
    duration: '5 years from commercial production',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Telangana MSME Promotion Policy 2024',
    sourceUrl: 'https://kipfinancial.com/telangana-state-specific-subsidy-benefits-for-msme-units/',
  },
  {
    id: 'tg-6', state: 'Telangana',
    name: 'Stamp Duty Reimbursement',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: '100% reimbursement on property deeds and loan documentation',
    eligibility: 'All eligible MSME manufacturing units',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Telangana MSME Promotion Policy 2024',
    sourceUrl: 'https://kipfinancial.com/telangana-state-specific-subsidy-benefits-for-msme-units/',
  },

  // ── RAJASTHAN ─────────────────────────────────────────────────────────────
  {
    id: 'rj-1', state: 'Rajasthan',
    name: 'SGST Investment Subsidy — Area Category 1',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '75% of Net SGST as investment subsidy',
    eligibility: 'New/expansion eligible units in Category 1 areas',
    duration: '7 years',
    enterpriseSize: ['micro', 'small', 'medium', 'large'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Rajasthan Investment Promotion Scheme (RIPS) 2022',
    sourceUrl: 'https://legalman.in/rajasthan-investment-promotion-scheme-2022-rips-2022-simplified-guidelines/',
  },
  {
    id: 'rj-2', state: 'Rajasthan',
    name: 'Capital Subsidy — Backward Areas',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: 'Up to 28% of eligible investment for thrust sectors in Category 2 & 3',
    eligibility: 'Units investing in Area Category 2 and 3 backward regions',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'RIPS 2022',
    sourceUrl: 'https://360subsidy.com/rips.html',
  },
  {
    id: 'rj-3', state: 'Rajasthan',
    name: 'Stamp Duty Exemption',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: 'Up to 75% exemption on stamp duty and land conversion charges',
    eligibility: 'All new eligible enterprises (pre-commercial phase)',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium', 'large'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'RIPS 2022',
    sourceUrl: 'https://legalman.in/rajasthan-investment-promotion-scheme-2022-rips-2022-simplified-guidelines/',
  },
  {
    id: 'rj-4', state: 'Rajasthan',
    name: 'Employment Training Subsidy',
    type: 'employment', sectors: ['manufacturing'],
    amount: '₹4,000/worker/month for 6 months training',
    eligibility: 'Units creating new employment in Rajasthan',
    duration: '6 months per eligible worker',
    enterpriseSize: ['micro', 'small', 'medium', 'large'], newOnly: false, forWomen: false, forScSt: false,
    policyName: 'RIPS 2022',
    sourceUrl: 'https://360subsidy.com/rips.html',
  },

  // ── UTTAR PRADESH ─────────────────────────────────────────────────────────
  {
    id: 'up-1', state: 'Uttar Pradesh',
    name: 'Interest Subvention — Micro Industries',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '50% discount on annual interest payable, max ₹25 lakh/unit',
    eligibility: 'New micro industries',
    duration: '5 years',
    enterpriseSize: ['micro'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'UP MSME Promotion Policy 2022',
    sourceUrl: 'https://invest.up.gov.in/uttar-pradesh-micro-small-medium-enterprises-promotion-policy-2022/',
  },
  {
    id: 'up-2', state: 'Uttar Pradesh',
    name: 'Interest Subvention — Women / SC-ST Micro',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '60% interest subvention, max ₹25 lakh/unit',
    eligibility: 'Women or SC/ST entrepreneurs in micro manufacturing sector',
    duration: '5 years',
    enterpriseSize: ['micro'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'UP MSME Promotion Policy 2022',
    sourceUrl: 'https://invest.up.gov.in/uttar-pradesh-micro-small-medium-enterprises-promotion-policy-2022/',
  },
  {
    id: 'up-3', state: 'Uttar Pradesh',
    name: 'Stamp Duty Exemption — Purvanchal / Bundelkhand',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: '100% stamp duty exemption',
    eligibility: 'All MSMEs in Purvanchal and Bundelkhand regions',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'UP MSME Promotion Policy 2022',
    sourceUrl: 'https://kipfinancial.com/stamp-duty-exemption-scheme-for-uttar-pradesh-msmes/',
  },
  {
    id: 'up-4', state: 'Uttar Pradesh',
    name: 'Stamp Duty Exemption — Women Entrepreneurs (All of UP)',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: '100% stamp duty exemption anywhere in Uttar Pradesh',
    eligibility: 'Women entrepreneurs starting any MSME unit',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: true, forScSt: false,
    policyName: 'UP MSME Promotion Policy 2022',
    sourceUrl: 'https://invest.up.gov.in/uttar-pradesh-micro-small-medium-enterprises-promotion-policy-2022/',
  },
  {
    id: 'up-5', state: 'Uttar Pradesh',
    name: 'Clean Technology Financial Assistance',
    type: 'other', sectors: ['manufacturing'],
    amount: 'Up to ₹20 lakhs for adopting certified clean/green technology',
    eligibility: 'MSME units adopting certified clean technology',
    duration: 'Per project',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: false, forWomen: false, forScSt: false,
    policyName: 'UP MSME Promotion Policy 2022',
    sourceUrl: 'https://invest.up.gov.in/uttar-pradesh-micro-small-medium-enterprises-promotion-policy-2022/',
  },

  // ── MADHYA PRADESH ────────────────────────────────────────────────────────
  {
    id: 'mp-1', state: 'Madhya Pradesh',
    name: 'Basic Investment Promotion Assistance (BIPA)',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '40% for investment ≤₹10 cr in plant & machinery; tiered down to 10% for larger investments',
    eligibility: 'New and expansion manufacturing units',
    duration: 'Per policy schedule',
    enterpriseSize: ['micro', 'small', 'medium', 'large'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Madhya Pradesh Industrial Promotion Policy 2025',
    sourceUrl: 'https://finraja.com/madhya-pradesh-industrial-promotion-policy-2025/',
  },
  {
    id: 'mp-2', state: 'Madhya Pradesh',
    name: 'Women/SC-ST Additional Benefit',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: 'Additional 2% p.a. for 4 years on investments ≤₹10 crore',
    eligibility: 'Women and SC/ST entrepreneurs',
    duration: '4 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'MP Industrial Promotion Policy 2025',
    sourceUrl: 'https://finraja.com/madhya-pradesh-industrial-promotion-policy-2025/',
  },
  {
    id: 'mp-3', state: 'Madhya Pradesh',
    name: 'Electricity Duty Exemption',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '100% electricity duty exemption (garments: 7 years; others: 5 years)',
    eligibility: 'New manufacturing units across all sectors',
    duration: '5–7 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'MP Industrial Promotion Policy 2025',
    sourceUrl: 'https://finraja.com/madhya-pradesh-industrial-promotion-policy-2025/',
  },
  {
    id: 'mp-4', state: 'Madhya Pradesh',
    name: 'Interest Subsidy — Garments',
    type: 'interest-subsidy', sectors: ['textile'],
    amount: '5% p.a. for 7 years',
    eligibility: 'Garment manufacturing units',
    duration: '7 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'MP Industrial Promotion Policy 2025',
    sourceUrl: 'https://finraja.com/madhya-pradesh-industrial-promotion-policy-2025/',
  },
  {
    id: 'mp-5', state: 'Madhya Pradesh',
    name: 'Green Infrastructure Capital Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '50% on waste management infra, max ₹5 crore; max ₹10 crore for ZLD effluent treatment',
    eligibility: 'All eligible manufacturing units investing in pollution control',
    duration: 'One-time',
    enterpriseSize: ['small', 'medium', 'large'], newOnly: false, forWomen: false, forScSt: false,
    policyName: 'MP Industrial Promotion Policy 2025',
    sourceUrl: 'https://finraja.com/madhya-pradesh-industrial-promotion-policy-2025/',
  },

  // ── HARYANA ───────────────────────────────────────────────────────────────
  {
    id: 'hr-1', state: 'Haryana',
    name: 'SGST Reimbursement — Block C/D',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '75% Net SGST for 7 years, then 35% for 3 years; cap 100–150% of FCI',
    eligibility: 'MSMEs in Block C and D categories (backward/underdeveloped districts)',
    duration: '10 years total',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Haryana Enterprises and Employment Policy (HEEP) 2020',
    sourceUrl: 'https://msme.haryana.gov.in/haryana-enterprises-and-employment-policy-2020/',
  },
  {
    id: 'hr-2', state: 'Haryana',
    name: 'Stamp Duty Refund',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: 'Block D: 100%; Block C: 75%; Block B: 50%',
    eligibility: 'Industrial land purchases/leases within 5 years of commercial production',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium', 'large'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'HEEP 2020',
    sourceUrl: 'https://osganconsultants.com/haryana-enterprises-and-employment-policy-2020-heep-2020/',
  },
  {
    id: 'hr-3', state: 'Haryana',
    name: 'Electricity Duty Exemption',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '100% exemption (Block D: 10 years, Block C: 7 years, Block B: 5 years)',
    eligibility: 'New industrial units in B, C, D category blocks',
    duration: '5–10 years',
    enterpriseSize: ['micro', 'small', 'medium', 'large'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'HEEP 2020',
    sourceUrl: 'https://osganconsultants.com/haryana-enterprises-and-employment-policy-2020-heep-2020/',
  },
  {
    id: 'hr-4', state: 'Haryana',
    name: 'Employment Generation Subsidy — Women / SC-ST',
    type: 'employment', sectors: ['manufacturing'],
    amount: '₹48,000/worker/year for women, SC-ST, or differently-abled (vs ₹36,000 general)',
    eligibility: 'Units employing 50+ workers with priority given to women/SC-ST',
    duration: '7 years',
    enterpriseSize: ['small', 'medium', 'large'], newOnly: false, forWomen: true, forScSt: true,
    policyName: 'HEEP 2020',
    sourceUrl: 'https://osganconsultants.com/haryana-enterprises-and-employment-policy-2020-heep-2020/',
  },
  {
    id: 'hr-5', state: 'Haryana',
    name: 'Rural Micro Enterprise Capital Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '15% on plant & machinery, max ₹15 lakhs (₹25 lakh for Women/SC/ST)',
    eligibility: 'Micro enterprises outside municipal limits in rural B/C/D blocks',
    duration: 'One-time',
    enterpriseSize: ['micro'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'HEEP 2020 — Gramin Yojana',
    sourceUrl: 'https://kipfinancial.com/special-benefits-to-msme-in-haryana/',
  },

  // ── PUNJAB ────────────────────────────────────────────────────────────────
  {
    id: 'pb-1', state: 'Punjab',
    name: 'Capital Investment Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '50% of Fixed Capital Investment, max ₹50 lakhs',
    eligibility: 'New micro and small manufacturing units',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Punjab Industrial Policy 2022',
    sourceUrl: 'https://pbindustries.gov.in/static/why_punjab;Key=Fiscal_Incentives_MSME_units',
  },
  {
    id: 'pb-2', state: 'Punjab',
    name: 'SGST Reimbursement',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '100% of Net SGST, cap at 100% of FCI',
    eligibility: 'All eligible new MSME units',
    duration: '7 years from commercial production',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Punjab Industrial Policy 2022',
    sourceUrl: 'https://services.india.gov.in/service/detail/investment-subsidy-by-way-of-reimbursement-of-net-sgstvat-from-department-of-industries-and-commerce-in-punjab',
  },
  {
    id: 'pb-3', state: 'Punjab',
    name: 'Electricity Duty Exemption',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '100% exemption on electricity duty',
    eligibility: 'All new MSME manufacturing units',
    duration: '7 years from power connection',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Punjab Industrial Policy 2022',
    sourceUrl: 'https://pbindustries.gov.in/static/why_punjab;Key=Fiscal_Incentives_MSME_units',
  },
  {
    id: 'pb-4', state: 'Punjab',
    name: 'Interest Subsidy — Border / Women / SC Districts',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '5% p.a., max ₹5 lakh/year',
    eligibility: 'Units in border/Kandi districts, or women/SC entrepreneurs anywhere in Punjab',
    duration: '5 years',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'Punjab Industrial Policy 2022',
    sourceUrl: 'https://kipfinancial.com/msme-units-specific-benefits-in-punjab/',
  },

  // ── KERALA ────────────────────────────────────────────────────────────────
  {
    id: 'kl-1', state: 'Kerala',
    name: 'Capital Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: 'Up to 30% of capital investment, max ₹30 lakhs',
    eligibility: 'New/expansion MSME manufacturing units',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Kerala Industrial Policy 2023',
    sourceUrl: 'https://www.niir.org/blog/kerala-industrial-subsidy-for-manufacturing/',
  },
  {
    id: 'kl-2', state: 'Kerala',
    name: 'Interest Subvention on Term Loans',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '3%–6% interest subsidy on term loans from scheduled banks',
    eligibility: 'MSME manufacturing units',
    duration: 'Max 5 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: false, forWomen: false, forScSt: false,
    policyName: 'Kerala Industrial Policy 2023',
    sourceUrl: 'https://industry.kerala.gov.in/index.php/scheme-for-interest-subvention-on-term-loan-and-working-capital-loan-iss-schemes',
  },
  {
    id: 'kl-3', state: 'Kerala',
    name: 'Stamp Duty Waiver',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: '100% waiver of stamp duty and registration charges',
    eligibility: 'Units buying/leasing land in government or notified private industrial parks',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Kerala Industrial Policy 2023',
    sourceUrl: 'https://industry.kerala.gov.in/images/pdf/2023/IND_POLICY_ENG.pdf',
  },
  {
    id: 'kl-4', state: 'Kerala',
    name: 'Power Tariff Subsidy',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '₹1/unit reduction on electricity bills',
    eligibility: 'MSME manufacturing units (LT/HT connections)',
    duration: 'First 3 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Kerala Industrial Policy 2023',
    sourceUrl: 'https://www.niir.org/blog/kerala-industrial-subsidy-for-manufacturing/',
  },

  // ── ANDHRA PRADESH ────────────────────────────────────────────────────────
  {
    id: 'ap-1', state: 'Andhra Pradesh',
    name: 'Capital Subsidy — General',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '25% of FCI; max ₹25L (micro), ₹1.5Cr (small), ₹7Cr (medium)',
    eligibility: 'New/expansion MSME manufacturing units',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'AP MSME & Entrepreneurship Development Policy 4.0 (2024–29)',
    sourceUrl: 'https://kipfinancial.com/andhra-pradesh-msme-and-entrepreneurship-development-policy-4-0-2024-2029-3/',
  },
  {
    id: 'ap-2', state: 'Andhra Pradesh',
    name: 'Enhanced Capital Subsidy — Women / BC / SC-ST',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '35% of FCI, max ₹7 crore',
    eligibility: 'Women, BC, SC, ST, or specially-abled entrepreneurs',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'AP MSME Policy 4.0 (2024–29)',
    sourceUrl: 'https://kipfinancial.com/andhra-pradesh-msme-and-entrepreneurship-development-policy-4-0-2024-2029-3/',
  },
  {
    id: 'ap-3', state: 'Andhra Pradesh',
    name: 'SGST Reimbursement',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '100% SGST; annual cap at 5% of turnover; total cap ≤100% of FCI',
    eligibility: 'All MSME manufacturing units post commercial production',
    duration: '5 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'AP MSME Policy 4.0 (2024–29)',
    sourceUrl: 'https://kipfinancial.com/andhra-pradesh-msme-and-entrepreneurship-development-policy-4-0-2024-2029-3/',
  },
  {
    id: 'ap-4', state: 'Andhra Pradesh',
    name: 'Power Tariff Concession',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '₹1/unit for first 5 years',
    eligibility: 'Micro and small manufacturing units',
    duration: '5 years',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'AP Industrial Policy 2020–23',
    sourceUrl: 'https://www.mondaq.com/india/fiscal-monetary-policy/980788/andhra-pradesh-industrial-policy-2020-2023-an-overview',
  },

  // ── ODISHA ────────────────────────────────────────────────────────────────
  {
    id: 'od-1', state: 'Odisha',
    name: 'Capital Investment Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '25% on machinery, max ₹2 crore',
    eligibility: 'New/expansion MSME manufacturing units',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Odisha MSME Development Policy 2022',
    sourceUrl: 'https://kipfinancial.com/know-about-the-subsidy-benefits-in-odisha-state/',
  },
  {
    id: 'od-2', state: 'Odisha',
    name: 'Capital Subsidy — SC/ST / Women',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '30% on machinery, max ₹2.5 crore',
    eligibility: 'SC/ST, women, or technically qualified entrepreneurs',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'Odisha MSME Development Policy 2022',
    sourceUrl: 'https://kipfinancial.com/know-about-the-subsidy-benefits-in-odisha-state/',
  },
  {
    id: 'od-3', state: 'Odisha',
    name: 'Interest Subsidy',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '50% of interest paid on term loan (e.g., 10% loan → effective 5%)',
    eligibility: 'All MSME units with bank term loan',
    duration: 'Per loan tenure',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: false, forWomen: false, forScSt: false,
    policyName: 'Odisha MSME Development Policy 2022',
    sourceUrl: 'https://kipfinancial.com/know-about-the-subsidy-benefits-in-odisha-state/',
  },
  {
    id: 'od-4', state: 'Odisha',
    name: 'Electricity Duty Exemption',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '100% exemption (for units with ≤750 KVA connected load)',
    eligibility: 'Fresh MSME units within specified connected load limit',
    duration: 'First 5 years',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Odisha MSME Development Policy 2022',
    sourceUrl: 'https://kipfinancial.com/know-about-the-subsidy-benefits-in-odisha-state/',
  },
  {
    id: 'od-5', state: 'Odisha',
    name: 'Land Conversion Exemption',
    type: 'other', sectors: ['manufacturing'],
    amount: '100% exemption on agri-to-industrial land conversion charges, up to 5 acres',
    eligibility: 'All new MSME units converting agricultural land',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Odisha MSME Development Policy 2022',
    sourceUrl: 'https://kipfinancial.com/know-about-the-subsidy-benefits-in-odisha-state/',
  },

  // ── WEST BENGAL ───────────────────────────────────────────────────────────
  {
    id: 'wb-1', state: 'West Bengal',
    name: 'Capital Investment Subsidy — Banglashree',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '20–40% of FCI depending on zone; higher for Women/SC/ST/Minority',
    eligibility: 'MSMEs applying under Banglashree scheme',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'Banglashree MSME Incentive Scheme 2020-25',
    sourceUrl: 'https://silpasathi.wb.gov.in/msme_Incentives',
  },
  {
    id: 'wb-2', state: 'West Bengal',
    name: 'Interest Subsidy',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '55–70% reduction in effective interest for micro/small in most zones',
    eligibility: 'Micro and small enterprises under Banglashree',
    duration: 'Per loan tenure',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Banglashree MSME Incentive Scheme 2020-25',
    sourceUrl: 'https://silpasathi.wb.gov.in/msme_Incentives',
  },
  {
    id: 'wb-3', state: 'West Bengal',
    name: 'Textile Capital Subsidy',
    type: 'capital-subsidy', sectors: ['textile'],
    amount: 'Max ₹20 crore–₹50 crore depending on investment size',
    eligibility: 'Textile sector enterprises across the full value chain',
    duration: 'One-time',
    enterpriseSize: ['small', 'medium', 'large'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'West Bengal Textile Incentive Scheme 2022',
    sourceUrl: 'https://www.apparelviews.com/west-bengal-launches-textile-incentive-scheme-2022/',
  },
  {
    id: 'wb-4', state: 'West Bengal',
    name: 'Power Subsidy — Textile',
    type: 'electricity', sectors: ['textile'],
    amount: 'Up to ₹1 crore/year (garments: ₹50L/year) as power cost reimbursement',
    eligibility: 'Garment and textile manufacturing units',
    duration: '5 years',
    enterpriseSize: ['small', 'medium', 'large'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'West Bengal Textile Incentive Scheme 2022',
    sourceUrl: 'https://www.apparelviews.com/west-bengal-launches-textile-incentive-scheme-2022/',
  },

  // ── UTTARAKHAND ───────────────────────────────────────────────────────────
  {
    id: 'uk-1', state: 'Uttarakhand',
    name: 'Capital Subsidy — Category A (Mountain/Backward)',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '50% on investment ≤₹1 crore; additional 25% on investment ₹1–5 crore (max ₹1.5 crore total)',
    eligibility: 'MSMEs in Category A mountain/backward areas',
    duration: 'Instalment-based disbursement',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Uttarakhand MSME/Industrial Development Policy 2023',
    sourceUrl: 'https://www.niir.org/blog/government-schemes-for-industries-in-uttarakhand/',
  },
  {
    id: 'uk-2', state: 'Uttarakhand',
    name: 'Capital Subsidy — Category B',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '40% on investment ≤₹1 crore',
    eligibility: 'MSMEs in Category B areas',
    duration: 'Instalment-based disbursement',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Uttarakhand MSME/Industrial Development Policy 2023',
    sourceUrl: 'https://www.niir.org/blog/government-schemes-for-industries-in-uttarakhand/',
  },
  {
    id: 'uk-3', state: 'Uttarakhand',
    name: 'Stamp Duty Exemption',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: 'Exemption on industrial land purchase/lease',
    eligibility: 'All eligible MSMEs',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Uttarakhand Industrial Development Policy',
    sourceUrl: 'https://doiuk.org/mysite/policies',
  },

  // ── HIMACHAL PRADESH ──────────────────────────────────────────────────────
  {
    id: 'hp-1', state: 'Himachal Pradesh',
    name: 'Capital Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '25% of Fixed Capital Investment',
    eligibility: 'New/expansion MSME manufacturing units',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'HP Industrial Investment Policy 2019',
    sourceUrl: 'https://msmedihimachal.nic.in/pages/view/146/210-annexure-ii-incentive-to-industries-in-h.p.',
  },
  {
    id: 'hp-2', state: 'Himachal Pradesh',
    name: 'Interest Subvention',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '4% p.a. on term loans, max ₹20 lakh/year',
    eligibility: 'New/expansion MSME manufacturing units',
    duration: '3–5 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'HP Industrial Investment Policy 2019',
    sourceUrl: 'https://knnindia.co.in/news/newsdetails/state/himachal-cabinet-approves-industrial-investment-policy-2019-enhances-incentives-to-msmes',
  },
  {
    id: 'hp-3', state: 'Himachal Pradesh',
    name: 'SGST Reimbursement',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: 'Net SGST reimbursed for 7 years, max 80% of FCI',
    eligibility: 'All eligible manufacturing units',
    duration: '7 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'HP Industrial Investment Policy 2019',
    sourceUrl: 'https://knnindia.co.in/news/newsdetails/state/himachal-cabinet-approves-industrial-investment-policy-2019-enhances-incentives-to-msmes',
  },
  {
    id: 'hp-4', state: 'Himachal Pradesh',
    name: 'Industrial Estate Lease Rental Subsidy',
    type: 'other', sectors: ['manufacturing'],
    amount: '50% in Year 1 (max ₹2L); 40% in Year 2 (max ₹1L); 25% in Years 3–5',
    eligibility: 'New units set up in government industrial estates',
    duration: '5 years',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'HP Industrial Investment Policy 2019',
    sourceUrl: 'https://msmedihimachal.nic.in/pages/view/146/210-annexure-ii-incentive-to-industries-in-h.p.',
  },

  // ── JHARKHAND ─────────────────────────────────────────────────────────────
  {
    id: 'jh-1', state: 'Jharkhand',
    name: 'Capital Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '25% of FCI; max ₹1Cr (micro), ₹5Cr (small), ₹10Cr (medium)',
    eligibility: 'New/expansion manufacturing units',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Jharkhand Industrial and Investment Promotion Policy 2021',
    sourceUrl: 'https://www.nsws.gov.in/s3fs/2022-10/Jharkhand%20Industrial%20and%20Investment%20Policy%202021.pdf',
  },
  {
    id: 'jh-2', state: 'Jharkhand',
    name: 'Additional Capital Subsidy — SC/ST / Women',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: 'Additional 5% over the standard rate',
    eligibility: 'SC/ST, women, or differently-abled entrepreneurs',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'Jharkhand Industrial and Investment Promotion Policy 2021',
    sourceUrl: 'https://www.nsws.gov.in/s3fs/2022-10/Jharkhand%20Industrial%20and%20Investment%20Policy%202021.pdf',
  },
  {
    id: 'jh-3', state: 'Jharkhand',
    name: 'Interest Subsidy',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '5% p.a.; max ₹15L (micro), ₹50L (small), ₹1Cr (medium)',
    eligibility: 'All MSMEs with bank term loan',
    duration: '5 years from commercial production',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Jharkhand Industrial and Investment Promotion Policy 2021',
    sourceUrl: 'https://www.nsws.gov.in/s3fs/2022-10/Jharkhand%20Industrial%20and%20Investment%20Policy%202021.pdf',
  },
  {
    id: 'jh-4', state: 'Jharkhand',
    name: 'SGST Reimbursement',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '100% of Net SGST, max 100% of total FCI',
    eligibility: 'New MSME units post commercial production',
    duration: '5 years (large: 7 years, mega: 9 years)',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Jharkhand Industrial and Investment Promotion Policy 2021',
    sourceUrl: 'https://www.nsws.gov.in/s3fs/2022-10/Jharkhand%20Industrial%20and%20Investment%20Policy%202021.pdf',
  },

  // ── BIHAR ─────────────────────────────────────────────────────────────────
  {
    id: 'br-1', state: 'Bihar',
    name: 'Capital/Interest Subvention — Priority Sectors',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '10% or actual (whichever lower); max 30% of project cost; overall cap ₹10 crore',
    eligibility: 'All new/expansion manufacturing units in priority sectors',
    duration: 'Per project term',
    enterpriseSize: ['micro', 'small', 'medium', 'large'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Bihar Industrial Investment Promotion Policy (BIIPP) 2016',
    sourceUrl: 'https://hebe.net.in/highlights-of-bihar-industrial-investment-promotion-policy-2016-with-latest-amendments/',
  },
  {
    id: 'br-2', state: 'Bihar',
    name: 'SC/ST / Women Enhanced Subvention',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '11.5% or actual; max 34.5% of project cost; cap ₹11.5 crore',
    eligibility: 'SC/ST, women, or differently-abled entrepreneurs',
    duration: 'Per project term',
    enterpriseSize: ['micro', 'small', 'medium', 'large'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'BIIPP 2016',
    sourceUrl: 'https://hebe.net.in/highlights-of-bihar-industrial-investment-promotion-policy-2016-with-latest-amendments/',
  },
  {
    id: 'br-3', state: 'Bihar',
    name: 'SGST Reimbursement — High Priority Sectors',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '100% admitted SGST; cap 100% of project cost',
    eligibility: 'Units in high-priority sectors (food processing, IT, etc.)',
    duration: '5 years',
    enterpriseSize: ['micro', 'small', 'medium', 'large'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'BIIPP 2016',
    sourceUrl: 'https://hebe.net.in/highlights-of-bihar-industrial-investment-promotion-policy-2016-with-latest-amendments/',
  },
  {
    id: 'br-4', state: 'Bihar',
    name: 'Electricity Duty Reimbursement',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '100% reimbursement on electricity duty',
    eligibility: 'All eligible manufacturing units',
    duration: '5 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'BIIPP 2016',
    sourceUrl: 'https://hebe.net.in/highlights-of-bihar-industrial-investment-promotion-policy-2016-with-latest-amendments/',
  },

  // ── ASSAM ─────────────────────────────────────────────────────────────────
  {
    id: 'as-1', state: 'Assam',
    name: 'SGST Reimbursement',
    type: 'gst-reimbursement', sectors: ['manufacturing'],
    amount: '100% SGST; micro: cap 200% of FCI; small: cap 150% of FCI',
    eligibility: 'New/expansion manufacturing units in Assam',
    duration: 'Up to 15 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Industrial and Investment Policy of Assam (IIP) 2019',
    sourceUrl: 'https://aiinvestmentpolicy.assam.gov.in/',
  },
  {
    id: 'as-2', state: 'Assam',
    name: 'Power Subsidy',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '₹2/unit for 5 years, max ₹50 lakhs/year; cap 100% of plant & machinery investment',
    eligibility: 'All eligible manufacturing units',
    duration: '5 years',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'IIP Assam 2019',
    sourceUrl: 'https://sgmconsultancyservices.co.in/iip-assam-2019/',
  },
  {
    id: 'as-3', state: 'Assam',
    name: 'Stamp Duty Reimbursement',
    type: 'stamp-duty', sectors: ['manufacturing'],
    amount: '100% reimbursement, max ₹25 lakhs',
    eligibility: 'New units purchasing non-agricultural, non-urban land',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'IIP Assam 2019',
    sourceUrl: 'https://sgmconsultancyservices.co.in/iip-assam-2019/',
  },
  {
    id: 'as-4', state: 'Assam',
    name: 'Generator Set Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '50% of cost, max ₹20 lakhs',
    eligibility: 'All MSME manufacturing units requiring backup power',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: false, forWomen: false, forScSt: false,
    policyName: 'IIP Assam 2019',
    sourceUrl: 'https://sgmconsultancyservices.co.in/iip-assam-2019/',
  },

  // ── CHHATTISGARH ──────────────────────────────────────────────────────────
  {
    id: 'cg-1', state: 'Chhattisgarh',
    name: 'Capital Subsidy (FCI) — MSMEs',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '30%–45% of FCI depending on district group; max ₹60L–₹5 crore',
    eligibility: 'New/expansion MSME manufacturing units',
    duration: 'Disbursed in 1 (micro), 3 (small), or 5 (medium) equal instalments',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'Chhattisgarh Industrial Development Policy 2024–30',
    sourceUrl: 'https://finraja.com/chhattisgarh-industrial-policy-2024-30-subsidy-consultancy/',
  },
  {
    id: 'cg-2', state: 'Chhattisgarh',
    name: 'SC/ST / Women Margin Money Subsidy',
    type: 'capital-subsidy', sectors: ['manufacturing'],
    amount: '25% margin money subsidy, max ₹100 lakhs',
    eligibility: 'SC/ST, women, and designated entrepreneur categories',
    duration: 'One-time',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: true, forScSt: true,
    policyName: 'CG Industrial Development Policy 2024–30',
    sourceUrl: 'https://finraja.com/chhattisgarh-industrial-policy-2024-30-subsidy-consultancy/',
  },
  {
    id: 'cg-3', state: 'Chhattisgarh',
    name: 'Electricity Duty Exemption',
    type: 'electricity', sectors: ['manufacturing'],
    amount: '100% exemption from commercial production date',
    eligibility: 'New MSME enterprises',
    duration: 'Group 1: 5 yrs, Group 2: 6 yrs, Group 3: 9 yrs',
    enterpriseSize: ['micro', 'small', 'medium'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'CG Industrial Development Policy 2024–30',
    sourceUrl: 'https://finraja.com/chhattisgarh-industrial-policy-2024-30-subsidy-consultancy/',
  },
  {
    id: 'cg-4', state: 'Chhattisgarh',
    name: 'Interest Subsidy',
    type: 'interest-subsidy', sectors: ['manufacturing'],
    amount: '40%–70% of interest on loans, ₹10–25 lakhs/year',
    eligibility: 'Micro and small industries',
    duration: '5–7 years depending on area group',
    enterpriseSize: ['micro', 'small'], newOnly: true, forWomen: false, forScSt: false,
    policyName: 'CG Industrial Development Policy 2024–30',
    sourceUrl: 'https://finraja.com/chhattisgarh-industrial-policy-2024-30-subsidy-consultancy/',
  },
  {
    id: 'cg-5', state: 'Chhattisgarh',
    name: 'EPF Employment Subsidy',
    type: 'employment', sectors: ['manufacturing'],
    amount: '75% of employer EPF contribution, max ₹1 crore/year',
    eligibility: 'Manufacturing units hiring Chhattisgarh-domiciled workers',
    duration: 'Per policy terms',
    enterpriseSize: ['small', 'medium', 'large'], newOnly: false, forWomen: false, forScSt: false,
    policyName: 'CG Industrial Development Policy 2024–30',
    sourceUrl: 'https://finraja.com/chhattisgarh-industrial-policy-2024-30-subsidy-consultancy/',
  },
]

// ─── Metadata maps ────────────────────────────────────────────────────────────

export const ALL_STATES = [...new Set(INCENTIVES.map(i => i.state))].sort()

export const TYPE_META: Record<IncentiveType, { label: string; color: string; icon: string }> = {
  'capital-subsidy':   { label: 'Capital Subsidy',     icon: '💰', color: 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300' },
  'interest-subsidy':  { label: 'Interest Subsidy',    icon: '📉', color: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300' },
  'stamp-duty':        { label: 'Stamp Duty Relief',   icon: '📄', color: 'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300' },
  'electricity':       { label: 'Electricity Concession', icon: '⚡', color: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/40 dark:text-yellow-300' },
  'gst-reimbursement': { label: 'GST Reimbursement',   icon: '🔄', color: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300' },
  'employment':        { label: 'Employment Subsidy',  icon: '👷', color: 'bg-teal-100 text-teal-700 dark:bg-teal-900/40 dark:text-teal-300' },
  'tax-holiday':       { label: 'Tax Holiday',         icon: '🏖️', color: 'bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300' },
  'other':             { label: 'Other Benefit',       icon: '✨', color: 'bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300' },
}

export const SIZE_META: Record<EnterpriseSizeKey, { label: string; color: string }> = {
  micro:  { label: 'Micro',  color: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300' },
  small:  { label: 'Small',  color: 'bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300' },
  medium: { label: 'Medium', color: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300' },
  large:  { label: 'Large',  color: 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300' },
}
