import { NextResponse } from 'next/server'
import { getNicByCode } from '@/lib/local-radar/nic-codes'
import { fetchPlacesTemporal } from '@/lib/local-radar/places-temporal'
import { getIncorporationTrend, getMcaSummary } from '@/lib/local-radar/mca21-static'
import { fetchMca21Live } from '@/lib/local-radar/mca21'
import { fetchUdyamData } from '@/lib/local-radar/udyam'
import { estimateGstinCount } from '@/lib/local-radar/gstin'
import type { RadarResult, YearCount, DataSource } from '@/lib/local-radar/types'
import { readFile } from 'fs/promises'
import path from 'path'

export const runtime = 'nodejs'
// No revalidate — each query is unique (city + nicCode)

// Geocode a city + state string using Google Geocoding API
async function geocode(city: string, state: string, apiKey: string): Promise<{ lat: number; lng: number } | null> {
  try {
    const q = encodeURIComponent(`${city}, ${state}, India`)
    const res = await fetch(
      `https://maps.googleapis.com/maps/api/geocode/json?address=${q}&key=${apiKey}`,
      { next: { revalidate: 86400 } }
    )
    const data = await res.json()
    const loc = data.results?.[0]?.geometry?.location
    return loc ? { lat: loc.lat, lng: loc.lng } : null
  } catch { return null }
}

// Merge trajectories from multiple sources into a unified year-series
function mergeTrajectories(sources: { data: YearCount[]; weight: number }[]): YearCount[] {
  const yearMap = new Map<number, { counts: number[]; sources: DataSource[] }>()

  for (const { data } of sources) {
    for (const item of data) {
      const existing = yearMap.get(item.year) ?? { counts: [], sources: [] }
      existing.counts.push(item.count)
      if (!existing.sources.includes(item.source)) existing.sources.push(item.source)
      yearMap.set(item.year, existing)
    }
  }

  return [...yearMap.entries()]
    .sort(([a], [b]) => a - b)
    .map(([year, { counts, sources }]) => ({
      year,
      count: Math.round(counts.reduce((a, b) => a + b, 0) / counts.length), // average if multi-source
      source: sources[0] as DataSource,
    }))
}

function computeTrend(trajectory: YearCount[]): { trend: RadarResult['trend']; reason: string; velocity: number } {
  if (trajectory.length < 2) return { trend: 'Stable', reason: 'Insufficient data for trend analysis', velocity: 0 }

  const recent = trajectory.slice(-3)
  const older  = trajectory.slice(0, -3)

  const recentAvg = recent.reduce((a, b) => a + b.count, 0) / recent.length
  const olderAvg  = older.length ? older.reduce((a, b) => a + b.count, 0) / older.length : recentAvg

  const velocity = olderAvg > 0 ? (recentAvg - olderAvg) / olderAvg : 0

  // Check if total counts are small (emerging market)
  const totalCount = trajectory.reduce((a, b) => a + b.count, 0)
  const lastYearCount = trajectory.at(-1)?.count ?? 0

  if (totalCount < 10 && velocity >= 0) {
    return { trend: 'Emerging', reason: `Fewer than 10 tracked entries — early-stage market with ${lastYearCount} recent entrants`, velocity }
  }

  if (velocity > 0.3) {
    return {
      trend: 'Rising',
      reason: `Entry rate grew ${Math.round(velocity * 100)}% vs 3-year average — strong demand signal`,
      velocity,
    }
  }

  if (velocity > 0.1) {
    return { trend: 'Rising', reason: `Steady ${Math.round(velocity * 100)}% growth in new entrants`, velocity }
  }

  if (velocity < -0.2) {
    return {
      trend: 'Declining',
      reason: `Entry rate fell ${Math.round(Math.abs(velocity) * 100)}% — possible market saturation or reduced viability`,
      velocity,
    }
  }

  // Check absolute level — if high count + stable = saturating
  if (lastYearCount > 50) {
    return { trend: 'Saturating', reason: `High entry volume (${lastYearCount}/year) with flat growth — market maturing`, velocity }
  }

  return { trend: 'Stable', reason: `Entry rate stable at ~${Math.round(recentAvg)} new businesses/year`, velocity }
}

interface Mca21ProcessedResult {
  cityByYear: Record<number, number>          // city-level incorporation counts
  stateByYear: Record<number, number>         // state-level incorporation counts (extrapolated)
  activeCount: number
  struckOffCount: number
  survivalRate: number
}

// Load preprocessed MCA21 summary (generated by scripts/fetch-mca21.mjs)
async function loadMca21Processed(state: string, city: string, nicDivision: string): Promise<Mca21ProcessedResult | null> {
  try {
    const filePath = path.join(process.cwd(), 'public', 'data', 'mca21', 'summary.json')
    const raw = await readFile(filePath, 'utf-8')
    const data = JSON.parse(raw)

    // State-level (always available if state was processed)
    const stateNicData = data.byStateNicYear?.[state]?.[nicDivision]
    if (!stateNicData) return null

    const stateByYear: Record<number, number> = {}
    let activeCount = 0, struckOffCount = 0
    for (const [y, v] of Object.entries(stateNicData)) {
      const val = v as { active: number; struckOff: number }
      stateByYear[parseInt(y)] = (val.active ?? 0) + (val.struckOff ?? 0)
      activeCount    += val.active    ?? 0
      struckOffCount += val.struckOff ?? 0
    }

    // City-level (best effort — may not exist for smaller cities)
    const cityData = data.byCityNicYear?.[city]?.[nicDivision]
    const cityByYear: Record<number, number> = {}
    if (cityData) {
      for (const [y, v] of Object.entries(cityData)) {
        const val = v as { active: number; struckOff: number }
        cityByYear[parseInt(y)] = (val.active ?? 0) + (val.struckOff ?? 0)
      }
    }

    const total = activeCount + struckOffCount
    return {
      cityByYear,
      stateByYear,
      activeCount,
      struckOffCount,
      survivalRate: total > 0 ? Math.round(activeCount / total * 100) : 0,
    }
  } catch { return null }
}

export async function GET(req: Request) {
  const startMs = Date.now()
  const { searchParams } = new URL(req.url)

  const nicCode  = searchParams.get('nic') ?? ''
  const city     = searchParams.get('city') ?? ''
  const state    = searchParams.get('state') ?? ''
  const radiusKm = parseFloat(searchParams.get('radius') ?? '15')

  if (!nicCode || !city || !state) {
    return NextResponse.json({ error: 'Required: nic, city, state' }, { status: 400 })
  }

  const nic = getNicByCode(nicCode)
  if (!nic) return NextResponse.json({ error: `Unknown NIC code: ${nicCode}` }, { status: 400 })

  const apiKey = process.env.GOOGLE_MAPS_API_KEY
  if (!apiKey) return NextResponse.json({ error: 'GOOGLE_MAPS_API_KEY not set' }, { status: 500 })

  // 1. Geocode city
  const coords = await geocode(city, state, apiKey)
  if (!coords) return NextResponse.json({ error: `Could not geocode: ${city}, ${state}` }, { status: 422 })

  // 2. All sources in parallel — Places (slowest), Udyam, MCA21 preprocessed file, MCA21 live API
  const [placesResult, udyamResult, mca21Processed, mca21Live] = await Promise.all([
    fetchPlacesTemporal(coords.lat, coords.lng, radiusKm, nic.placeKeywords, apiKey, 25),
    fetchUdyamData(state, city, nicCode),
    loadMca21Processed(state, city, nic.division),
    fetchMca21Live(state, nic.division),
  ])

  // 3. MCA21 — priority: preprocessed file (real data) > live API sample > static hardcoded fallback
  const mcaStatic = getMcaSummary(state, nic.division)
  const mcaTrend  = getIncorporationTrend(state, nic.division)

  const mca21Source: 'preprocessed' | 'api_sample' | 'static_fallback' =
    mca21Processed ? 'preprocessed' :
    mca21Live      ? 'api_sample'   :
    'static_fallback'

  // Trajectory: prefer city-level preprocessed, then state-level preprocessed, then live API, then static
  const mca21Trajectory: YearCount[] =
    (mca21Processed && Object.keys(mca21Processed.cityByYear).length > 0)
      ? Object.entries(mca21Processed.cityByYear)
          .map(([y, c]) => ({ year: parseInt(y), count: c, source: 'mca21' as const }))
          .sort((a, b) => a.year - b.year)
    : mca21Processed
      ? Object.entries(mca21Processed.stateByYear)
          .map(([y, c]) => ({ year: parseInt(y), count: c, source: 'mca21' as const }))
          .sort((a, b) => a.year - b.year)
    : mca21Live
      ? Object.entries(mca21Live.incorporationsByYear)
          .map(([y, c]) => ({ year: parseInt(y), count: c, source: 'mca21' as const }))
          .sort((a, b) => a.year - b.year)
    : mcaTrend

  const mca21ActiveCount  = mca21Processed?.activeCount  ?? mca21Live?.activeCount  ?? mcaStatic?.activeCount
  const mca21StruckOff    = mca21Processed?.struckOffCount ?? mca21Live?.struckOffCount ?? mcaStatic?.struckOffCount
  const mca21SurvivalRate = mca21Processed?.survivalRate  ?? mca21Live?.survivalRate  ?? mcaStatic?.survivalRate
  const mca21Note         = mca21Live?.note

  // 4. GSTIN estimate
  const gstinEst = estimateGstinCount(state, nic.division)

  // 5. Merge trajectory — only use city-level sources for trend.
  // MCA21 state-level counts are 10-100× larger than city-level Places counts,
  // so only include MCA21 in the merge when we have city-level preprocessed data.
  const cityLevelSources: { data: YearCount[]; weight: number }[] = [
    { data: placesResult.trajectory, weight: 3 },
    { data: udyamResult.trajectory, weight: 2 },
  ]
  if (mca21Source === 'preprocessed' && mca21Processed && Object.keys(mca21Processed.cityByYear).length > 0) {
    cityLevelSources.push({ data: mca21Trajectory, weight: 2 })
  }

  const mergedTrajectory = mergeTrajectories(cityLevelSources)

  const { trend, reason, velocity } = computeTrend(mergedTrajectory)

  const trajectoryBySource: RadarResult['trajectoryBySource'] = {
    google_places: placesResult.trajectory,
    mca21:         mca21Trajectory,
    udyam:         udyamResult.trajectory,
    gstin:         [],  // GSTIN doesn't give year-level breakdown
  }

  const result: RadarResult = {
    businessType: nic.label,
    nicCode,
    city,
    state,
    lat:     coords.lat,
    lng:     coords.lng,
    radiusKm,

    trajectory:         mergedTrajectory,
    trajectoryBySource,

    currentCount:  placesResult.currentCount,
    closedCount:   placesResult.closedCount,
    survivalRate:  placesResult.survivalRate,
    businesses:    placesResult.businesses.slice(0, 30),

    entryVelocity: Math.round(velocity * 100),
    trend,
    trendReason:   reason,

    mcaStateSummary: (mca21Processed || mca21Live || mcaStatic) ? {
      state,
      nicDivision:          nic.division,
      incorporationsByYear: mca21Processed?.stateByYear ?? mca21Live?.incorporationsByYear ?? mcaStatic?.incorporationsByYear ?? {},
      activeCount:          mca21ActiveCount ?? 0,
      struckOffCount:       mca21StruckOff ?? 0,
      survivalRate:         mca21SurvivalRate ?? 0,
    } : undefined,

    udyamSummary: {
      district: city,
      nicCode,
      registrationsByYear: udyamResult.byYear,
      totalCount:          udyamResult.totalCount,
      source:              udyamResult.source,
      note:                udyamResult.note,
    },

    gstinEstimate: gstinEst ? {
      state,
      count: gstinEst.sectorEstimate,
      note:  gstinEst.note,
    } : undefined,

    sourcesSummary: [
      {
        source:      'google_places',
        status:      'live',
        description: `Live Google Places search — ${placesResult.businesses.length} businesses found, review-date temporal analysis`,
        count:       placesResult.businesses.length,
      },
      {
        source:      'mca21',
        status:      mca21Source === 'preprocessed' ? 'live'
                   : mca21Source === 'api_sample'   ? 'live'
                   : 'estimated',
        description: mca21Source === 'preprocessed'
          ? `MCA21 company master (preprocessed file) — city-level incorporations for NIC ${nic.division}`
          : mca21Source === 'api_sample'
          ? (mca21Note ?? `MCA21 state-level data via data.gov.in API — NIC ${nic.division} companies in ${state}`)
          : `MCA Annual Report statistics (hardcoded fallback) — run scripts/fetch-mca21.mjs to get real data`,
        count: mca21ActiveCount,
      },
      {
        source:      'udyam',
        status:      udyamResult.source === 'api' ? 'live' : 'unavailable',
        description: udyamResult.source === 'api'
          ? `data.gov.in Udyam API — district MSME registrations for NIC ${nicCode}`
          : (udyamResult.note ?? 'Set DATA_GOV_IN_API_KEY to enable'),
        count: udyamResult.totalCount,
      },
      {
        source:      'gstin',
        status:      gstinEst ? 'estimated' : 'unavailable',
        description: gstinEst
          ? `GSTN Annual Statistics — estimated ${gstinEst.sectorEstimate.toLocaleString()} active GST filers in this sector in ${state}`
          : 'GSTIN bulk API not publicly available',
        count: gstinEst?.sectorEstimate,
      },
    ],

    generatedAt: new Date().toISOString(),
    durationMs:  Date.now() - startMs,
  }

  return NextResponse.json(result)
}
