// Static sector definitions — NIC 2-digit divisions with hardcoded signal priors.
// Dynamic signals (formation, survival) are computed from MCA21/Udyam in signals.ts.
// Static signals (credit, trade, employment, policy) are calibrated from:
//   - RBI Sectoral Bank Credit reports (quarterly)
//   - DGFT Annual Trade Statistics 2023-24
//   - EPFO Payroll data 2023-24
//   - Union Budget 2024-25 + PLI scheme announcements

import type { SectorCategory } from './types'

export interface SectorDef {
  nicCode: string
  label: string
  icon: string
  category: SectorCategory
  description: string
  trendsKeywords: string[]

  // Hardcoded signal priors (0-100)
  creditMomentum:       number   // RBI sectoral credit YoY growth → score
  creditNote:           string
  tradeExposure:        number   // export strength; 50 = balanced
  tradeNote:            string
  employmentAbsorption: number   // EPFO payroll quality score
  employmentNote:       string
  policyScore:          number   // PLI + budget tailwind
  policyNote:           string
  searchTrendsBase:     number   // baseline if live Trends API fails
}

export const SECTORS: SectorDef[] = [
  {
    nicCode: '01', label: 'Agriculture & Allied', icon: '🌾',
    category: 'Primary',
    description: 'Crop cultivation, animal husbandry, horticulture',
    trendsKeywords: ['farming india', 'agriculture startup'],
    creditMomentum: 62, creditNote: 'RBI farm credit grew 15% YoY; Kisan Credit Card push',
    tradeExposure: 55, tradeNote: '₹4.5L cr agri exports; rice, spices, marine products',
    employmentAbsorption: 82, employmentNote: '45% workforce; MGNREGS + PM-KISAN formalizing gig layer',
    policyScore: 68, policyNote: 'PM-KISAN, Agri Infra Fund, crop insurance push',
    searchTrendsBase: 45,
  },
  {
    nicCode: '10', label: 'Food Products', icon: '🥫',
    category: 'Manufacturing',
    description: 'Processed foods, dairy, grain milling, confectionery',
    trendsKeywords: ['food processing india', 'packaged food startup'],
    creditMomentum: 65, creditNote: 'PLI-boosted capex in food processing; NBFC lending up 22%',
    tradeExposure: 60, tradeNote: '$8.5B food exports; rice, marine, spices leading',
    employmentAbsorption: 75, employmentNote: '2nd largest MSME employer; EPFO additions steady at 8% YoY',
    policyScore: 78, policyNote: '₹10,900cr PLI for food processing; Mega Food Parks scheme',
    searchTrendsBase: 55,
  },
  {
    nicCode: '13', label: 'Textiles', icon: '🧵',
    category: 'Manufacturing',
    description: 'Spinning, weaving, fabric manufacturing, technical textiles',
    trendsKeywords: ['textile industry india', 'technical textiles'],
    creditMomentum: 42, creditNote: 'Credit under stress; NPAs elevated in spinning sector',
    tradeExposure: 72, tradeNote: '$38B textile exports; cotton yarn, fabrics, home textiles',
    employmentAbsorption: 80, employmentNote: '45M employed — 2nd largest employment sector after agri',
    policyScore: 72, policyNote: '₹10,683cr PLI for MMF and technical textiles; PM MITRA parks',
    searchTrendsBase: 42,
  },
  {
    nicCode: '14', label: 'Apparel & Garments', icon: '👗',
    category: 'Manufacturing',
    description: 'Ready-made garments, fashion, uniforms',
    trendsKeywords: ['garment industry india', 'apparel export'],
    creditMomentum: 48, creditNote: 'MSME credit tight; larger players accessing ECBs',
    tradeExposure: 78, tradeNote: '$16B garment exports; growing share in EU/US',
    employmentAbsorption: 85, employmentNote: 'Women-dominant workforce; EPFO net additions +12% FY24',
    policyScore: 65, policyNote: 'Scheme for Remission of Duties (RoDTEP); labour reforms',
    searchTrendsBase: 50,
  },
  {
    nicCode: '20', label: 'Chemicals & Pharma', icon: '🧪',
    category: 'Manufacturing',
    description: 'Basic chemicals, pharmaceuticals, agrochemicals, specialty chemicals',
    trendsKeywords: ['pharma india', 'specialty chemicals india'],
    creditMomentum: 70, creditNote: 'Strong Pharma PLI uptake; 18% credit growth in bulk drugs',
    tradeExposure: 80, tradeNote: '$27B pharma exports; generic leader; China+1 specialty chem play',
    employmentAbsorption: 65, employmentNote: 'Capital intensive; R&D employment growing 14% YoY',
    policyScore: 82, policyNote: '₹15,000cr PLI for pharma; bulk drug parks; China+1 policy push',
    searchTrendsBase: 52,
  },
  {
    nicCode: '22', label: 'Rubber & Plastics', icon: '🔧',
    category: 'Manufacturing',
    description: 'Rubber products, plastic goods, packaging',
    trendsKeywords: ['plastic manufacturing india', 'rubber products'],
    creditMomentum: 52, creditNote: 'Stable demand from auto + infra; credit growth 10% YoY',
    tradeExposure: 45, tradeNote: 'Import dependent for raw polymers; downstream exports growing',
    employmentAbsorption: 58, employmentNote: 'Mid-scale employment; automation replacing semi-skilled',
    policyScore: 45, policyNote: 'Single-use plastic ban creating disruption + opportunity',
    searchTrendsBase: 40,
  },
  {
    nicCode: '24', label: 'Basic Metals & Steel', icon: '⚙️',
    category: 'Manufacturing',
    description: 'Steel, aluminium, copper, ferrous/non-ferrous metals',
    trendsKeywords: ['steel industry india', 'aluminium manufacturing'],
    creditMomentum: 72, creditNote: 'Infra + housing boom; steel credit grew 20% YoY FY24',
    tradeExposure: 55, tradeNote: 'Net exporter but China competition compressing margins',
    employmentAbsorption: 60, employmentNote: 'Capital intensive; EPFO additions from downstream units',
    policyScore: 68, policyNote: 'National Steel Policy 300MT target; PLI for specialty steel',
    searchTrendsBase: 44,
  },
  {
    nicCode: '26', label: 'Electronics & Semiconductors', icon: '💾',
    category: 'Manufacturing',
    description: 'Mobile phones, semiconductors, consumer electronics, PCBs',
    trendsKeywords: ['electronics manufacturing india', 'semiconductor india'],
    creditMomentum: 78, creditNote: 'PLI-driven capex surge; credit to electronics up 28% FY24',
    tradeExposure: 35, tradeNote: '$85B electronics imports; Apple/Samsung push raising exports',
    employmentAbsorption: 70, employmentNote: 'EPFO additions surge near PLI factories in Tamil Nadu/UP',
    policyScore: 92, policyNote: '$10B semiconductor mission; ₹41,000cr PLI for electronics',
    searchTrendsBase: 62,
  },
  {
    nicCode: '27', label: 'Electrical Equipment', icon: '🔌',
    category: 'Manufacturing',
    description: 'Motors, switchgear, wires, cables, white goods',
    trendsKeywords: ['electrical equipment india', 'EV components'],
    creditMomentum: 68, creditNote: 'PLI for white goods + solar; credit up 17%',
    tradeExposure: 50, tradeNote: 'Growing exports of switchgear; import parity improving',
    employmentAbsorption: 65, employmentNote: 'Organized manufacturing base; EV component surge',
    policyScore: 76, policyNote: '₹6,238cr PLI for white goods; EV ecosystem incentives',
    searchTrendsBase: 48,
  },
  {
    nicCode: '29', label: 'Motor Vehicles & EV', icon: '🚗',
    category: 'Manufacturing',
    description: 'Automobiles, two-wheelers, EVs, auto components',
    trendsKeywords: ['electric vehicle india', 'automobile industry india'],
    creditMomentum: 74, creditNote: 'Auto credit grew 22% FY24; EV financing ecosystem building',
    tradeExposure: 62, tradeNote: '$21B auto exports; India becoming global EV hub',
    employmentAbsorption: 72, employmentNote: '4.5Cr direct + indirect employment; EV adding net jobs',
    policyScore: 88, policyNote: 'PM E-DRIVE ₹10,900cr; FAME III; PLI for auto ₹25,938cr',
    searchTrendsBase: 68,
  },
  {
    nicCode: '35', label: 'Energy & Power', icon: '⚡',
    category: 'Infrastructure',
    description: 'Electricity generation, renewables, solar, wind, gas',
    trendsKeywords: ['solar energy india', 'renewable energy business'],
    creditMomentum: 80, creditNote: 'Green financing at record highs; IREDA, REC lending strong',
    tradeExposure: 40, tradeNote: 'Import-dependent on solar panels; reducing with Make in India',
    employmentAbsorption: 62, employmentNote: 'Solar installation boom creating mass employment',
    policyScore: 92, policyNote: '500GW renewable target; ₹19,500cr solar PLI; green H2 mission',
    searchTrendsBase: 58,
  },
  {
    nicCode: '41', label: 'Construction & Real Estate Dev', icon: '🏗️',
    category: 'Infrastructure',
    description: 'Building construction, infrastructure projects, civil works',
    trendsKeywords: ['construction business india', 'real estate developer'],
    creditMomentum: 76, creditNote: 'Housing boom; PMAY credit up 25%; infra capex ₹11L cr',
    tradeExposure: 20, tradeNote: 'Domestic sector; minimal direct trade exposure',
    employmentAbsorption: 90, employmentNote: '5.5Cr employment; largest absorber of migrant labor',
    policyScore: 74, policyNote: 'PM Awas Yojana 3cr houses; ₹10L cr infra capex FY25',
    searchTrendsBase: 60,
  },
  {
    nicCode: '46', label: 'Wholesale Trade (B2B)', icon: '🏭',
    category: 'Trade',
    description: 'B2B distribution, commodity trading, wholesale markets',
    trendsKeywords: ['wholesale business india', 'b2b distribution'],
    creditMomentum: 60, creditNote: 'Trade finance growing; supply chain financing up 18%',
    tradeExposure: 50, tradeNote: 'Intermediary role; margin compression from direct D2C',
    employmentAbsorption: 68, employmentNote: 'Large informal base; formalizing via ONDC, GeM',
    policyScore: 52, policyNote: 'ONDC creating digitized wholesale layer; GeM integration',
    searchTrendsBase: 42,
  },
  {
    nicCode: '47', label: 'Retail Trade', icon: '🛒',
    category: 'Trade',
    description: 'Brick-and-mortar retail, supermarkets, specialty stores',
    trendsKeywords: ['retail business india', 'quick commerce india'],
    creditMomentum: 64, creditNote: 'Kirana digitization via UPI; MSME retail credit up 15%',
    tradeExposure: 25, tradeNote: 'Primarily domestic; some import-retail exposure (electronics)',
    employmentAbsorption: 78, employmentNote: '4Cr+ employment; quick commerce gig layer additive',
    policyScore: 58, policyNote: 'FDI in multi-brand retail still restricted; DPIIT e-commerce rules',
    searchTrendsBase: 65,
  },
  {
    nicCode: '49', label: 'Road Transport & Logistics', icon: '🚛',
    category: 'Logistics',
    description: 'Freight transport, trucking, last-mile delivery, courier',
    trendsKeywords: ['logistics startup india', 'trucking business india'],
    creditMomentum: 68, creditNote: 'Vehicle finance strong; CV loans up 20%; Udaan, Shiprocket ecosystem',
    tradeExposure: 45, tradeNote: 'Enabling export infrastructure; PM Gati Shakti multiplier',
    employmentAbsorption: 82, employmentNote: '22M truck drivers alone; gig delivery adding 5M+/yr',
    policyScore: 70, policyNote: 'PM Gati Shakti NMP; logistics policy aiming 8%→5% GDP cost',
    searchTrendsBase: 58,
  },
  {
    nicCode: '52', label: 'Warehousing & Cold Chain', icon: '🏬',
    category: 'Logistics',
    description: '3PL warehouses, cold storage, fulfillment centers',
    trendsKeywords: ['warehousing business india', 'cold chain logistics'],
    creditMomentum: 72, creditNote: 'Ecommerce + quick commerce driving warehouse demand; REITs fueling',
    tradeExposure: 48, tradeNote: 'Export-enabling; cold chain critical for agri exports',
    employmentAbsorption: 70, employmentNote: 'Automated warehouses + gig pickers; net employment growing',
    policyScore: 72, policyNote: '₹2L cr cold chain investment plan; PLI for food storage',
    searchTrendsBase: 54,
  },
  {
    nicCode: '55', label: 'Hotels & Accommodation', icon: '🏨',
    category: 'Hospitality',
    description: 'Hotels, resorts, homestays, budget accommodation',
    trendsKeywords: ['hotel business india', 'homestay business india'],
    creditMomentum: 62, creditNote: 'Post-COVID recovery; hospitality credit normalized; ADR at highs',
    tradeExposure: 55, tradeNote: 'Tourism receipts: foreign + domestic; G20 boost',
    employmentAbsorption: 78, employmentNote: '7.5Cr direct + indirect employment; strong EPFO recovery',
    policyScore: 60, policyNote: 'Swadesh Darshan 2.0; prasad scheme; 100 tourist destinations',
    searchTrendsBase: 58,
  },
  {
    nicCode: '56', label: 'Restaurants & Food Service', icon: '🍽️',
    category: 'Hospitality',
    description: 'Restaurants, QSR, cloud kitchens, catering, food delivery',
    trendsKeywords: ['restaurant business india', 'cloud kitchen india'],
    creditMomentum: 65, creditNote: 'F&B credit recovering strongly; cloud kitchen VC activity high',
    tradeExposure: 30, tradeNote: 'Domestic-focused; some export via ready meals and FMCDs',
    employmentAbsorption: 80, employmentNote: 'Zomato/Swiggy gig layer + kitchen staff = 7M+ jobs',
    policyScore: 52, policyNote: 'FSSAI licensing reforms; EoDB improvements in licensing',
    searchTrendsBase: 70,
  },
  {
    nicCode: '62', label: 'IT & Software', icon: '💻',
    category: 'Services',
    description: 'Software development, IT services, SaaS, data engineering',
    trendsKeywords: ['software startup india', 'IT services india'],
    creditMomentum: 72, creditNote: 'Startup ecosystem at $110B+ funding; IT credit growing 15%',
    tradeExposure: 95, tradeNote: '$227B IT exports FY24; world\'s largest IT services exporter',
    employmentAbsorption: 78, employmentNote: '5.4M direct IT employees; EPFO formal employment leader',
    policyScore: 75, policyNote: 'IndiaAI mission ₹10,372cr; Digital India; data center PLI',
    searchTrendsBase: 75,
  },
  {
    nicCode: '64', label: 'Financial Services & FinTech', icon: '🏦',
    category: 'Services',
    description: 'Banking, NBFCs, FinTech, payments, lending, wealth management',
    trendsKeywords: ['fintech startup india', 'neobank india'],
    creditMomentum: 82, creditNote: 'MSME lending boom; personal loans +30%; UPI-credit stack growing',
    tradeExposure: 42, tradeNote: 'GIFT City IFSC building cross-border services hub',
    employmentAbsorption: 72, employmentNote: 'FinTech hiring surging; traditional banking optimizing',
    policyScore: 78, policyNote: 'GIFT IFSC; ONDC financial layer; RBI sandbox programs',
    searchTrendsBase: 68,
  },
  {
    nicCode: '65', label: 'Insurance', icon: '🛡️',
    category: 'Services',
    description: 'Life, health, general, and crop insurance',
    trendsKeywords: ['insurance startup india', 'health insurance india'],
    creditMomentum: 58, creditNote: 'InsurTech attracting significant capital; bancassurance growing',
    tradeExposure: 30, tradeNote: 'Largely domestic; reinsurance export via GIFT City nascent',
    employmentAbsorption: 65, employmentNote: 'Agency model creating mass microentrepreneur layer',
    policyScore: 70, policyNote: 'Insurance for All by 2047; composite license reform; FDI to 74%',
    searchTrendsBase: 55,
  },
  {
    nicCode: '68', label: 'Real Estate', icon: '🏠',
    category: 'Services',
    description: 'Property development, brokerage, leasing, REITs',
    trendsKeywords: ['real estate investment india', 'property startup india'],
    creditMomentum: 74, creditNote: 'Housing credit at decade high; REITs maturing; data centers hot',
    tradeExposure: 20, tradeNote: 'Domestic; GCC and data center play linking to FDI flows',
    employmentAbsorption: 68, employmentNote: 'Construction linked; white-collar PropTech jobs growing',
    policyScore: 65, policyNote: 'SWAMIH fund 2; RERA maturing; affordable housing push',
    searchTrendsBase: 62,
  },
  {
    nicCode: '72', label: 'R&D & Scientific Services', icon: '🔬',
    category: 'Services',
    description: 'Research institutions, contract research, testing labs, GCCs',
    trendsKeywords: ['research startup india', 'GCC india'],
    creditMomentum: 62, creditNote: 'GCC boom; VC into deep tech; R&D credit incentives',
    tradeExposure: 70, tradeNote: 'GCCs exporting R&D services; $60B+ GCC revenues projected',
    employmentAbsorption: 68, employmentNote: '1.6M in GCCs growing 10%/yr; PhD + postdoc pipeline',
    policyScore: 72, policyNote: 'Anusandhan NRF ₹50,000cr; deep tech startup policy',
    searchTrendsBase: 48,
  },
  {
    nicCode: '85', label: 'Education & EdTech', icon: '📚',
    category: 'Services',
    description: 'Schools, coaching, higher education, EdTech platforms',
    trendsKeywords: ['edtech india', 'education startup india'],
    creditMomentum: 58, creditNote: 'EdTech post-BYJU\'s: cautious; physical coaching credit stable',
    tradeExposure: 45, tradeNote: 'International students in India growing; NAAC export credential push',
    employmentAbsorption: 70, employmentNote: '9.4M teachers; EdTech adding micro-tutors at scale',
    policyScore: 68, policyNote: 'NEP 2020 implementation; PM e-Vidya; coding in schools',
    searchTrendsBase: 65,
  },
  {
    nicCode: '86', label: 'Healthcare & Medical', icon: '🏥',
    category: 'Services',
    description: 'Hospitals, clinics, diagnostics, HealthTech, medical devices',
    trendsKeywords: ['healthcare startup india', 'medical tourism india'],
    creditMomentum: 76, creditNote: 'Hospital capex boom; NaBH accreditation driving investment',
    tradeExposure: 65, tradeNote: 'Medical tourism $9B+; pharma link; device export growing',
    employmentAbsorption: 78, employmentNote: '7.5M healthcare workers; EPFO formal additions strong',
    policyScore: 80, policyNote: 'PM-ABHIM ₹64,180cr; ESIC expansion; Ayushman Bharat Digital',
    searchTrendsBase: 68,
  },
  {
    nicCode: '74', label: 'Professional Services', icon: '💼',
    category: 'Services',
    description: 'Advertising, consulting, design, market research, legal',
    trendsKeywords: ['consulting startup india', 'agency business india'],
    creditMomentum: 58, creditNote: 'Professional services credit moderate; self-funded MSME dominant',
    tradeExposure: 55, tradeNote: 'GCC-adjacent; global delivery of creative/consulting services',
    employmentAbsorption: 70, employmentNote: 'Gig economy largest contributor; Zoho/Freshworks growth',
    policyScore: 55, policyNote: 'Start-up India; DPIIT recognition benefits; EoDB push',
    searchTrendsBase: 50,
  },
  {
    nicCode: '82', label: 'Business Support Services', icon: '📞',
    category: 'Services',
    description: 'BPO, KPO, call centers, facility management, payroll',
    trendsKeywords: ['BPO india', 'outsourcing business india'],
    creditMomentum: 55, creditNote: 'Maturing sector; AI disruption risk priced in',
    tradeExposure: 72, tradeNote: 'BPO/KPO: $40B+ export revenue; AI augmenting not replacing',
    employmentAbsorption: 75, employmentNote: '1.4M in formal BPO; AI transition upskilling underway',
    policyScore: 58, policyNote: 'Work-from-home policy clarity needed; STPI expansion',
    searchTrendsBase: 45,
  },
  {
    nicCode: '96', label: 'Personal & Beauty Services', icon: '✂️',
    category: 'Services',
    description: 'Salons, wellness, laundry, tailoring, personal care',
    trendsKeywords: ['salon business india', 'wellness startup india'],
    creditMomentum: 55, creditNote: 'MSME credit stable; beauty startup VC growing',
    tradeExposure: 20, tradeNote: 'Primarily domestic; cosmetics import dependency',
    employmentAbsorption: 76, employmentNote: '12M+ unorganized workers formalizing via Udyam',
    policyScore: 50, policyNote: 'PMKVY skilling; MSME support; cottage industry classification',
    searchTrendsBase: 62,
  },
  {
    nicCode: '45', label: 'Motor Vehicle Trade & Repair', icon: '🔩',
    category: 'Trade',
    description: 'Auto dealerships, spare parts, vehicle repair, EV charging',
    trendsKeywords: ['auto dealership india', 'EV charging business'],
    creditMomentum: 70, creditNote: 'Vehicle loans at decade high; EV service center surge',
    tradeExposure: 35, tradeNote: 'Import-adjacent for parts; EV charging infra domestic',
    employmentAbsorption: 72, employmentNote: '4.5M mechanics + dealership staff; EV retooling ongoing',
    policyScore: 72, policyNote: 'FAME III + PM E-DRIVE; scrappage policy boosting replacement demand',
    searchTrendsBase: 55,
  },
]

export function getSectorByNic(nicCode: string): SectorDef | undefined {
  return SECTORS.find(s => s.nicCode === nicCode)
}
