export interface ExportCategory {
  id: string
  name: string
  hsCode: string
  sector: string
  exportValueUSD: number     // FY 2023-24, USD billion
  growthYoY: number          // % change vs FY 2022-23
  indiaGlobalRank: number    // India's rank in global exports of this category
  globalMarketSharePct: number
  topMarkets: { country: string; sharePct: number }[]
  avgRealisationPerKg: number // USD (approx)
  activeExporters: number    // approximate registered exporters
  opportunityScore: number   // 0–100 composite score (growth + rank + margins + SME accessibility)
  smeAccessibility: 'high' | 'medium' | 'low'  // can an individual/SME participate?
  minOrderValue: string      // rough entry order size
  keyStates: string[]
  certifications: string[]   // common buyer requirements
  seasonality: string
  overview: string
  tailwinds: string[]
}

// Sources: DGFT Annual Report FY2024, APEDA, Ministry of Commerce Export Statistics,
// Commerce Ministry press releases, WTO Trade Statistics 2023
export const EXPORT_CATEGORIES: ExportCategory[] = [
  // ── AGRICULTURE ──────────────────────────────────────────────────────────
  {
    id: 'basmati-rice',
    name: 'Basmati Rice',
    hsCode: '1006.30',
    sector: 'Agriculture',
    exportValueUSD: 4.81,
    growthYoY: 12,
    indiaGlobalRank: 1,
    globalMarketSharePct: 65,
    topMarkets: [{ country: 'Saudi Arabia', sharePct: 22 }, { country: 'Iran', sharePct: 18 }, { country: 'Iraq', sharePct: 12 }, { country: 'UAE', sharePct: 10 }, { country: 'USA', sharePct: 7 }],
    avgRealisationPerKg: 1.20,
    activeExporters: 2800,
    opportunityScore: 74,
    smeAccessibility: 'high',
    minOrderValue: '₹5–10L (1 FCL)',
    keyStates: ['Punjab', 'Haryana', 'Uttar Pradesh', 'Uttarakhand'],
    certifications: ['APEDA RCMC', 'Phytosanitary Certificate (NPPO)', 'GI Tag compliance for Basmati'],
    seasonality: 'Harvest Oct–Dec; exports year-round from stockpiles',
    overview: 'India dominates global basmati exports with 65% market share. Strong brand premium over Pakistani basmati. Post-COVID demand surge in Middle East continues.',
    tailwinds: ['Iran & Iraq demand growing', 'GI protection strengthening premium', 'India–UAE CEPA duty reduction to 0%'],
  },
  {
    id: 'spices',
    name: 'Spices & Spice Products',
    hsCode: '09',
    sector: 'Agriculture',
    exportValueUSD: 4.25,
    growthYoY: 8,
    indiaGlobalRank: 1,
    globalMarketSharePct: 25,
    topMarkets: [{ country: 'USA', sharePct: 16 }, { country: 'China', sharePct: 12 }, { country: 'Bangladesh', sharePct: 8 }, { country: 'UAE', sharePct: 7 }, { country: 'Vietnam', sharePct: 6 }],
    avgRealisationPerKg: 2.80,
    activeExporters: 9500,
    opportunityScore: 82,
    smeAccessibility: 'high',
    minOrderValue: '₹1–3L (small FCL)',
    keyStates: ['Kerala', 'Karnataka', 'Andhra Pradesh', 'Rajasthan', 'Gujarat'],
    certifications: ['Spices Board RCMC', 'APEDA', 'Phytosanitary Certificate', 'Organic (NOP/EU 834 for premium)'],
    seasonality: 'Pepper/cardamom: Oct–Jan; Chilli: Feb–Apr; Cumin: Mar–May',
    overview: 'India is the world\'s largest producer, consumer, and exporter of spices — 80+ varieties. Branded blended spices growing 3x faster than raw commodity exports. Premium organic segment fastest-growing in EU/USA.',
    tailwinds: ['Ethnic food boom in diaspora markets', 'Functional food trends (turmeric, ginger)', 'India–UK FTA in negotiation (15% tariff reduction expected)'],
  },
  {
    id: 'marine-products',
    name: 'Marine Products (Frozen Shrimp & Fish)',
    hsCode: '03',
    sector: 'Agriculture',
    exportValueUSD: 7.38,
    growthYoY: 4,
    indiaGlobalRank: 1,
    globalMarketSharePct: 18,
    topMarkets: [{ country: 'USA', sharePct: 31 }, { country: 'China', sharePct: 22 }, { country: 'EU', sharePct: 13 }, { country: 'Japan', sharePct: 10 }, { country: 'UAE', sharePct: 5 }],
    avgRealisationPerKg: 4.20,
    activeExporters: 1400,
    opportunityScore: 70,
    smeAccessibility: 'medium',
    minOrderValue: '₹20–50L (cold chain container)',
    keyStates: ['Andhra Pradesh', 'Gujarat', 'West Bengal', 'Kerala', 'Odisha'],
    certifications: ['MPEDA RCMC', 'HACCP', 'EU approved processing unit', 'USFDA registration', 'BAP (Best Aquaculture Practices)'],
    seasonality: 'Vannamei shrimp: year-round (aquaculture); wild catch: seasonal',
    overview: 'India is the world\'s largest exporter of frozen shrimp. Vannamei aquaculture in Andhra Pradesh is cost-competitive globally. US market growing at 7% CAGR for value-added seafood.',
    tailwinds: ['China shrimp demand recovery post-COVID', 'Value-added breaded shrimp growing in EU', 'India–UK FTA potential duty removal from 20%'],
  },
  {
    id: 'fresh-fruits-veg',
    name: 'Fresh Fruits & Vegetables',
    hsCode: '07–08',
    sector: 'Agriculture',
    exportValueUSD: 1.82,
    growthYoY: 7,
    indiaGlobalRank: 7,
    globalMarketSharePct: 3,
    topMarkets: [{ country: 'UAE', sharePct: 25 }, { country: 'Bangladesh', sharePct: 18 }, { country: 'Malaysia', sharePct: 8 }, { country: 'Nepal', sharePct: 6 }, { country: 'UK', sharePct: 5 }],
    avgRealisationPerKg: 0.75,
    activeExporters: 6000,
    opportunityScore: 65,
    smeAccessibility: 'high',
    minOrderValue: '₹2–5L',
    keyStates: ['Maharashtra', 'Andhra Pradesh', 'Karnataka', 'Tamil Nadu', 'Gujarat'],
    certifications: ['APEDA RCMC', 'Phytosanitary Certificate', 'EurepGAP/GlobalGAP for EU', 'Residue testing (Max Residue Limits)'],
    seasonality: 'Grapes: Jan–May; Mango: Apr–Jun; Onion: Oct–Apr; Pomegranate: Aug–Jan',
    overview: 'Largely untapped potential — India\'s rank (7th) is far below its agricultural production capacity (2nd globally). Cold chain and air freight costs are the key bottleneck. UAE and UK diaspora markets are high-premium outlets.',
    tailwinds: ['India–UAE CEPA zero-duty on 90%+ goods', 'Cold chain PLI scheme improving infra', 'Maharashtra Alphonso mango EU protocol resolved'],
  },
  {
    id: 'processed-food',
    name: 'Processed & Packaged Food',
    hsCode: '16–21',
    sector: 'Agriculture',
    exportValueUSD: 4.84,
    growthYoY: 11,
    indiaGlobalRank: 14,
    globalMarketSharePct: 2,
    topMarkets: [{ country: 'USA', sharePct: 18 }, { country: 'UAE', sharePct: 14 }, { country: 'Netherlands', sharePct: 8 }, { country: 'UK', sharePct: 7 }, { country: 'Australia', sharePct: 5 }],
    avgRealisationPerKg: 2.10,
    activeExporters: 3200,
    opportunityScore: 80,
    smeAccessibility: 'high',
    minOrderValue: '₹3–10L',
    keyStates: ['Maharashtra', 'Gujarat', 'Punjab', 'Karnataka', 'Tamil Nadu'],
    certifications: ['FSSAI Manufacturing License', 'APEDA RCMC', 'HACCP/ISO 22000', 'Halal (for Middle East/Malaysia)', 'Kosher (for USA/Israel)'],
    seasonality: 'Year-round',
    overview: 'Fastest-growing Indian export category. Demand from 35M+ Indian diaspora worldwide. RTE (Ready-to-Eat), ethnic snacks, and ayurvedic/herbal foods are premium growth segments. India severely under-indexed at rank 14 given agricultural base.',
    tailwinds: ['Diaspora-driven premium demand in USA/UK/Australia', 'Indian cuisine mainstream in Western markets', 'ONDC enabling small food brands to export', 'India–GCC FTA in negotiation'],
  },

  // ── HANDICRAFTS & TEXTILES ─────────────────────────────────────────────────
  {
    id: 'handicrafts',
    name: 'Handicrafts & Artisan Products',
    hsCode: '97',
    sector: 'Handicrafts & Art',
    exportValueUSD: 3.58,
    growthYoY: 6,
    indiaGlobalRank: 3,
    globalMarketSharePct: 7,
    topMarkets: [{ country: 'USA', sharePct: 28 }, { country: 'UAE', sharePct: 12 }, { country: 'UK', sharePct: 10 }, { country: 'Germany', sharePct: 8 }, { country: 'France', sharePct: 6 }],
    avgRealisationPerKg: 18.00,
    activeExporters: 7500,
    opportunityScore: 78,
    smeAccessibility: 'high',
    minOrderValue: '₹1–5L',
    keyStates: ['Uttar Pradesh', 'Rajasthan', 'West Bengal', 'Jammu & Kashmir', 'Gujarat'],
    certifications: ['EPCH RCMC', 'GI Tag (where applicable)', 'CE Mark (for electrical decoratives)', 'Lacquerware / Pashmina authentication'],
    seasonality: 'Peak orders Aug–Oct (US holiday season); Jan–Feb (Valentine\'s/Spring)',
    overview: 'Highly fragmented, cottage-industry led. Artisan clusters in Moradabad (brassware), Firozabad (glassware), Jaipur (textiles), Kutch (embroidery) have deep expertise. Direct-to-consumer via Etsy, Amazon Handmade growing 40%+ annually.',
    tailwinds: ['Etsy & Amazon Handmade enabling direct artisan exports', 'Sustainability trend favoring handmade over mass-produced', 'India\'s GI tags (350+) creating premium branding'],
  },
  {
    id: 'garments',
    name: 'Readymade Garments & Apparel',
    hsCode: '61–62',
    sector: 'Textiles',
    exportValueUSD: 16.20,
    growthYoY: -3,
    indiaGlobalRank: 5,
    globalMarketSharePct: 4,
    topMarkets: [{ country: 'USA', sharePct: 27 }, { country: 'EU', sharePct: 18 }, { country: 'UK', sharePct: 12 }, { country: 'UAE', sharePct: 6 }, { country: 'Canada', sharePct: 4 }],
    avgRealisationPerKg: 7.80,
    activeExporters: 12000,
    opportunityScore: 67,
    smeAccessibility: 'medium',
    minOrderValue: '₹10–30L (MOQ typically 500–1000 pcs per style)',
    keyStates: ['Tamil Nadu', 'Maharashtra', 'Delhi NCR', 'Gujarat', 'West Bengal'],
    certifications: ['AEPC RCMC', 'OEKO-TEX Standard 100', 'GOTS (Global Organic Textile Standard)', 'SA8000 (labor compliance)'],
    seasonality: 'Spring-Summer orders placed Sep–Nov; Fall-Winter orders placed Mar–May',
    overview: 'India is losing share to Bangladesh and Vietnam on labor cost. Opportunity lies in premium segments: designer wear, sustainable fashion, technical textiles, and niche ethnic wear (Banarasi, Kanjeevaram). China+1 benefiting primarily Vietnam but India gaining for premium buyers.',
    tailwinds: ['EU Carbon Border Adjustment — India\'s textile carbon intensity lower than China', 'India–UK FTA under negotiation (12% current tariff to 0%)', 'Sustainable & organic apparel premium 2–3× over conventional'],
  },
  {
    id: 'home-textiles',
    name: 'Home Textiles (Bed/Bath Linen)',
    hsCode: '63',
    sector: 'Textiles',
    exportValueUSD: 4.20,
    growthYoY: 5,
    indiaGlobalRank: 2,
    globalMarketSharePct: 11,
    topMarkets: [{ country: 'USA', sharePct: 55 }, { country: 'EU', sharePct: 20 }, { country: 'UK', sharePct: 8 }, { country: 'Australia', sharePct: 5 }, { country: 'Japan', sharePct: 3 }],
    avgRealisationPerKg: 5.20,
    activeExporters: 3500,
    opportunityScore: 75,
    smeAccessibility: 'medium',
    minOrderValue: '₹8–25L',
    keyStates: ['Gujarat', 'Rajasthan', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh'],
    certifications: ['TEXPROCIL RCMC', 'OEKO-TEX', 'GOTS', 'Fairtrade (for premium)'],
    seasonality: 'Year-round; peak Oct–Dec (US holiday and Back-to-School)',
    overview: 'India is the #2 global exporter (behind China) of bed linen, towels, and home furnishing textiles. Panipat is the world\'s recycled blanket capital. Karur (Tamil Nadu) dominates kitchen linen exports to the USA. Strong cost advantage over China + Turkey.',
    tailwinds: ['China+1 hotel procurement sourcing shift', 'Walmart, Target, and Ikea actively diversifying to India', 'PLI scheme for MMF (man-made fibre) technical textiles'],
  },

  // ── LEATHER & FOOTWEAR ────────────────────────────────────────────────────
  {
    id: 'leather-footwear',
    name: 'Leather & Leather Footwear',
    hsCode: '41, 64',
    sector: 'Leather',
    exportValueUSD: 3.75,
    growthYoY: 3,
    indiaGlobalRank: 6,
    globalMarketSharePct: 5,
    topMarkets: [{ country: 'USA', sharePct: 20 }, { country: 'Germany', sharePct: 16 }, { country: 'UK', sharePct: 12 }, { country: 'Italy', sharePct: 8 }, { country: 'France', sharePct: 7 }],
    avgRealisationPerKg: 9.50,
    activeExporters: 2200,
    opportunityScore: 65,
    smeAccessibility: 'medium',
    minOrderValue: '₹5–20L',
    keyStates: ['Tamil Nadu', 'Uttar Pradesh', 'West Bengal', 'Haryana', 'Punjab'],
    certifications: ['CLE RCMC', 'Leather Working Group (LWG) audit', 'REACH compliance (EU chemicals)', 'ISO 9001'],
    seasonality: 'Spring-Summer orders placed Sep–Nov; Fall-Winter orders placed Mar–May',
    overview: 'India is a major tannery and component supplier to global luxury brands (Gucci, LV, Clarks, Puma have Indian suppliers). Agra (footwear), Chennai/Ambur (tanneries), Kanpur (leather goods) are key clusters. Sustainability pressure growing — LWG certification becoming entry-ticket for EU buyers.',
    tailwinds: ['Luxury brands nearshoring from China', 'Chrome-free vegetable-tanned leather premium growing', 'India–UK FTA could eliminate 8–12% current duty'],
  },

  // ── PHARMACEUTICALS ───────────────────────────────────────────────────────
  {
    id: 'pharma-generic',
    name: 'Generic Pharmaceuticals & APIs',
    hsCode: '30',
    sector: 'Pharmaceuticals',
    exportValueUSD: 27.90,
    growthYoY: 7,
    indiaGlobalRank: 1,
    globalMarketSharePct: 20,
    topMarkets: [{ country: 'USA', sharePct: 31 }, { country: 'UK', sharePct: 9 }, { country: 'South Africa', sharePct: 7 }, { country: 'Russia', sharePct: 5 }, { country: 'Nigeria', sharePct: 4 }],
    avgRealisationPerKg: 52.00,
    activeExporters: 3000,
    opportunityScore: 72,
    smeAccessibility: 'low',
    minOrderValue: '₹50L+ (regulatory cost alone is high)',
    keyStates: ['Telangana', 'Andhra Pradesh', 'Gujarat', 'Maharashtra', 'Himachal Pradesh'],
    certifications: ['USFDA inspection clearance', 'EU GMP (EU Qualified Person)', 'WHO-GMP', 'Schedule M compliance', 'UKMHRA'],
    seasonality: 'Year-round',
    overview: 'India is the pharmacy of the world — largest volume generic exporter globally, supplying 40% of US generic prescriptions. API (Active Pharmaceutical Ingredients) manufacturing is highest margin segment. Entry barrier is very high (USFDA approvals take 3–5 years), but existing SMEs in Hyderabad/Vapi clusters can grow with incremental SKUs.',
    tailwinds: ['Post-COVID supply chain diversification from China', 'US Biosimilars market opening (India has 60+ approved biosimilar products)', 'Africa — growing demand for affordable generics'],
  },
  {
    id: 'ayurvedic-herbal',
    name: 'Ayurvedic & Herbal Products',
    hsCode: '1211, 30',
    sector: 'Pharmaceuticals',
    exportValueUSD: 0.82,
    growthYoY: 18,
    indiaGlobalRank: 1,
    globalMarketSharePct: 8,
    topMarkets: [{ country: 'USA', sharePct: 22 }, { country: 'Germany', sharePct: 12 }, { country: 'UAE', sharePct: 10 }, { country: 'UK', sharePct: 8 }, { country: 'Nepal', sharePct: 6 }],
    avgRealisationPerKg: 35.00,
    activeExporters: 1800,
    opportunityScore: 88,
    smeAccessibility: 'high',
    minOrderValue: '₹2–5L',
    keyStates: ['Uttarakhand', 'Himachal Pradesh', 'Kerala', 'Madhya Pradesh', 'Rajasthan'],
    certifications: ['AYUSH Premium Mark', 'NPOP Organic', 'US NOP Organic', 'EU Bio Siegel', 'WHO Traditional Medicine guidelines compliance'],
    seasonality: 'Year-round; herbal raw material procurement: monsoon and post-harvest',
    overview: 'Fastest-growing Indian pharma export category at 18% YoY. Global wellness market ($5.6T) accelerating demand for Ashwagandha, Turmeric, Amla, Moringa products. India has unique advantage as origin country for 85% of medicinal plant species used in Ayurveda.',
    tailwinds: ['Post-COVID immune supplement boom', 'EU Traditional Herbal Medicinal Products Directive opening', 'Ashwagandha KSM-66 patented extract growing 35% CAGR'],
  },

  // ── ENGINEERING & AUTO ────────────────────────────────────────────────────
  {
    id: 'auto-components',
    name: 'Auto Components & Parts',
    hsCode: '87.08',
    sector: 'Engineering',
    exportValueUSD: 20.10,
    growthYoY: 10,
    indiaGlobalRank: 5,
    globalMarketSharePct: 6,
    topMarkets: [{ country: 'USA', sharePct: 27 }, { country: 'Germany', sharePct: 11 }, { country: 'UK', sharePct: 8 }, { country: 'Thailand', sharePct: 6 }, { country: 'UAE', sharePct: 5 }],
    avgRealisationPerKg: 11.00,
    activeExporters: 5000,
    opportunityScore: 76,
    smeAccessibility: 'medium',
    minOrderValue: '₹10–30L',
    keyStates: ['Tamil Nadu', 'Maharashtra', 'Haryana', 'Karnataka', 'Gujarat'],
    certifications: ['IATF 16949 (Automotive QMS)', 'AEPC / ACMA RCMC', 'PPAP documentation', 'RoHS (for electronics components)'],
    seasonality: 'Year-round; tied to OEM production cycles',
    overview: 'India is supplier to Tier-1 auto parts firms globally. Chennai is the "Detroit of Asia." EV transition creating new opportunities in thermal management, battery enclosures, and EV-specific castings. USA and EU OEMs actively seeking India alternatives post-China trade war.',
    tailwinds: ['China+1 strategy — Suzuki, Hyundai, Toyota doubling India sourcing', 'EV component demand (new SKUs with less China competition)', 'India\'s PLI for auto components targets $56B exports by 2026'],
  },
  {
    id: 'light-engineering',
    name: 'Light Engineering Goods (Castings, Forgings, Fasteners)',
    hsCode: '73–83',
    sector: 'Engineering',
    exportValueUSD: 8.40,
    growthYoY: 12,
    indiaGlobalRank: 8,
    globalMarketSharePct: 3,
    topMarkets: [{ country: 'USA', sharePct: 22 }, { country: 'EU', sharePct: 18 }, { country: 'UK', sharePct: 10 }, { country: 'UAE', sharePct: 8 }, { country: 'Australia', sharePct: 5 }],
    avgRealisationPerKg: 3.80,
    activeExporters: 8000,
    opportunityScore: 73,
    smeAccessibility: 'medium',
    minOrderValue: '₹5–15L',
    keyStates: ['Gujarat', 'Maharashtra', 'Punjab', 'Tamil Nadu', 'Rajasthan'],
    certifications: ['EEPC RCMC', 'ISO 9001', 'CE Mark (for EU)', 'Material Test Certificate'],
    seasonality: 'Year-round',
    overview: 'Rajkot, Pune, and Ludhiana clusters are globally competitive in castings, forgings, and machined parts. India\'s cost advantage over Germany/Italy is 40–60% for comparable quality. German and UK SME buyers are actively sourcing from India as energy costs hurt European manufacturers.',
    tailwinds: ['European manufacturing cost crisis driving sourcing to India', 'Infrastructure capex in USA/Middle East driving castings demand', 'Semicon fab construction globally = new fasteners & precision parts demand'],
  },

  // ── ELECTRONICS ───────────────────────────────────────────────────────────
  {
    id: 'mobile-phones',
    name: 'Mobile Phones & Electronics',
    hsCode: '85.17',
    sector: 'Electronics',
    exportValueUSD: 15.60,
    growthYoY: 105,
    indiaGlobalRank: 5,
    globalMarketSharePct: 4,
    topMarkets: [{ country: 'USA', sharePct: 30 }, { country: 'UAE', sharePct: 18 }, { country: 'UK', sharePct: 9 }, { country: 'Netherlands', sharePct: 7 }, { country: 'Italy', sharePct: 5 }],
    avgRealisationPerKg: 210.00,
    activeExporters: 85,
    opportunityScore: 60,
    smeAccessibility: 'low',
    minOrderValue: 'N/A — only PLI-qualified OEMs',
    keyStates: ['Tamil Nadu', 'Karnataka', 'Andhra Pradesh', 'Uttar Pradesh'],
    certifications: ['PLI scheme registration', 'BIS CRS certification', 'FCC/CE for export markets'],
    seasonality: 'Year-round',
    overview: 'Apple iPhone assembly in India (Foxconn/Wistron/Pegatron in Chennai) is driving explosive growth. Samsung Galaxy manufactured in Noida. Not an SME opportunity directly — but component suppliers (packaging, cables, injection moulding, contract packaging) around these factories are growing rapidly.',
    tailwinds: ['Apple 25% India manufacturing target by 2025', 'Samsung diversifying assembly capacity', 'Component ecosystem building — connectors, PCBs, display covers'],
  },

  // ── CASTOR / NICHE CHEMICALS ──────────────────────────────────────────────
  {
    id: 'castor-oil',
    name: 'Castor Oil & Derivatives',
    hsCode: '15.15',
    sector: 'Chemicals',
    exportValueUSD: 0.95,
    growthYoY: 14,
    indiaGlobalRank: 1,
    globalMarketSharePct: 90,
    topMarkets: [{ country: 'China', sharePct: 45 }, { country: 'EU', sharePct: 18 }, { country: 'USA', sharePct: 12 }, { country: 'Bangladesh', sharePct: 5 }, { country: 'Japan', sharePct: 4 }],
    avgRealisationPerKg: 1.40,
    activeExporters: 350,
    opportunityScore: 85,
    smeAccessibility: 'medium',
    minOrderValue: '₹5–10L (1 ISO tank)',
    keyStates: ['Gujarat', 'Rajasthan', 'Andhra Pradesh'],
    certifications: ['Castor Oil RCMC (CHEMEXCIL)', 'REACH compliance (EU)', 'ISO 9001', 'Organic certificate (if bio-based derivatives)'],
    seasonality: 'Castor seed harvest: Nov–Jan; exports year-round from stockpiles',
    overview: 'India has 90% monopoly in global castor exports — no other country comes close. Used in lubricants, cosmetics, bioplastics, and biofuels. Hydrogenated and derivative forms (sebacic acid, 12-hydroxystearic acid) command 5–10× premium over crude oil. China is the dominant buyer but EU bio-economy demand growing.',
    tailwinds: ['EU ban on petroleum-based plasticizers driving bio-castor demand', 'Nylon-11 (from castor) for high-performance engineering plastics', 'Electric vehicles — castor-based lubricants'],
  },
  {
    id: 'organic-chemicals',
    name: 'Specialty Organic Chemicals & Dyes',
    hsCode: '29, 32',
    sector: 'Chemicals',
    exportValueUSD: 8.30,
    growthYoY: 9,
    indiaGlobalRank: 3,
    globalMarketSharePct: 8,
    topMarkets: [{ country: 'USA', sharePct: 22 }, { country: 'EU', sharePct: 20 }, { country: 'China', sharePct: 14 }, { country: 'Japan', sharePct: 10 }, { country: 'Taiwan', sharePct: 6 }],
    avgRealisationPerKg: 6.50,
    activeExporters: 1200,
    opportunityScore: 71,
    smeAccessibility: 'low',
    minOrderValue: '₹20–50L',
    keyStates: ['Gujarat', 'Maharashtra', 'Rajasthan'],
    certifications: ['CHEMEXCIL RCMC', 'REACH registration (EU)', 'ISO 9001', 'OEKO-TEX (for dyes)'],
    seasonality: 'Year-round',
    overview: 'Surat/Vapi (Gujarat) chemical clusters are globally competitive in reactive dyes, agrochemical intermediates, and fine chemicals. India is #2 producer of agrochemicals globally. China+1 diversification strongly benefiting Indian chemical exporters — API exports alone grew 35% since 2020.',
    tailwinds: ['China environmental crackdowns closing chemical units', 'Pharma API demand for India-made intermediates', 'Agri chemical demand in Latin America & Africa'],
  },

  // ── COFFEE & TEA ──────────────────────────────────────────────────────────
  {
    id: 'coffee',
    name: 'Coffee (Green & Processed)',
    hsCode: '09.01',
    sector: 'Agriculture',
    exportValueUSD: 1.10,
    growthYoY: 18,
    indiaGlobalRank: 6,
    globalMarketSharePct: 4,
    topMarkets: [{ country: 'Italy', sharePct: 18 }, { country: 'Germany', sharePct: 14 }, { country: 'Belgium', sharePct: 10 }, { country: 'USA', sharePct: 8 }, { country: 'Russia', sharePct: 7 }],
    avgRealisationPerKg: 3.60,
    activeExporters: 450,
    opportunityScore: 79,
    smeAccessibility: 'high',
    minOrderValue: '₹2–5L (specialty green coffee, small lots)',
    keyStates: ['Karnataka', 'Kerala', 'Tamil Nadu'],
    certifications: ['Coffee Board RCMC', 'Rainforest Alliance', 'UTZ / 4C Association', 'Organic (NOP/EU 834)', 'Fair Trade'],
    seasonality: 'Arabica harvest: Nov–Feb; Robusta: Nov–Jan; exports year-round',
    overview: 'India produces high-quality Arabica (Coorg, Chikmagalur) and Robusta (Wayanad). Specialty coffee market growing 20% CAGR globally. India is significantly under-priced vs Ethiopia/Colombia for equivalent quality — premium branding opportunity. Direct-trade model gaining traction with European specialty roasters.',
    tailwinds: ['Third-wave coffee culture driving specialty bean demand', 'Monsoon Malabar is globally unique — rare processing style', 'Japan and South Korea opening to Indian specialty coffee'],
  },
  {
    id: 'tea',
    name: 'Tea (Orthodox & CTC)',
    hsCode: '09.02',
    sector: 'Agriculture',
    exportValueUSD: 0.75,
    growthYoY: 2,
    indiaGlobalRank: 2,
    globalMarketSharePct: 12,
    topMarkets: [{ country: 'Russia', sharePct: 20 }, { country: 'UAE', sharePct: 15 }, { country: 'Iran', sharePct: 12 }, { country: 'UK', sharePct: 9 }, { country: 'Pakistan', sharePct: 7 }],
    avgRealisationPerKg: 2.90,
    activeExporters: 1100,
    opportunityScore: 64,
    smeAccessibility: 'medium',
    minOrderValue: '₹3–8L',
    keyStates: ['Assam', 'West Bengal', 'Tamil Nadu', 'Kerala'],
    certifications: ['Tea Board RCMC', 'Rainforest Alliance', 'ISO 3720', 'Organic (NOP/EU)'],
    seasonality: 'First flush: Mar–May; Second flush: Jun–Aug; Autumn: Oct–Nov',
    overview: 'India is the world\'s 2nd largest tea exporter. Darjeeling First Flush commands $50–$200/kg at auction (vs avg $2.9/kg). Sri Lanka gaining market share in some Orthodox segments. CTC tea dominated by commodity buyers. Opportunity: branded specialty teas (Darjeeling, Nilgiri, Assam estate) direct to Western consumers via D2C.',
    tailwinds: ['Darjeeling GI protection strengthening premium positioning', 'Wellness tea segment (functional, adaptogenic) growing 25% CAGR globally', 'Russia tea demand rebounding post-sanctions trade routing'],
  },

  // ── TOYS ─────────────────────────────────────────────────────────────────
  {
    id: 'toys',
    name: 'Toys & Games',
    hsCode: '95.03',
    sector: 'Manufacturing',
    exportValueUSD: 0.32,
    growthYoY: 45,
    indiaGlobalRank: 16,
    globalMarketSharePct: 0.5,
    topMarkets: [{ country: 'USA', sharePct: 24 }, { country: 'UK', sharePct: 16 }, { country: 'UAE', sharePct: 12 }, { country: 'Germany', sharePct: 8 }, { country: 'Australia', sharePct: 6 }],
    avgRealisationPerKg: 8.50,
    activeExporters: 280,
    opportunityScore: 92,
    smeAccessibility: 'high',
    minOrderValue: '₹2–5L',
    keyStates: ['Uttar Pradesh', 'Karnataka', 'Maharashtra', 'Rajasthan'],
    certifications: ['BIS IS 9873 (mandatory domestic + exports from India)', 'CE Mark (Europe)', 'ASTM F963 (USA)', 'EN 71 (EU)'],
    seasonality: 'Peak Q4 (Sep–Dec global holiday season)',
    overview: 'India imported $320M of toys 5 years ago, almost all from China. After BIS mandatory testing norms and high import duties, domestic production skyrocketed. Exports grew 300% in 3 years. Unique opportunity: wooden/traditional Indian toys (Channapatna, Kondapalli) are achieving premium in Western markets under handmade artisan positioning.',
    tailwinds: ['China+1 buying offices actively qualifying Indian toy factories', 'Channapatna wooden toys gaining EU/USA traction', 'PLI for toys attracting $1.4B investment to create export hubs'],
  },

  // ── FURNITURE ─────────────────────────────────────────────────────────────
  {
    id: 'furniture',
    name: 'Furniture & Wood Products',
    hsCode: '94',
    sector: 'Manufacturing',
    exportValueUSD: 0.48,
    growthYoY: 28,
    indiaGlobalRank: 18,
    globalMarketSharePct: 0.4,
    topMarkets: [{ country: 'USA', sharePct: 32 }, { country: 'UK', sharePct: 14 }, { country: 'UAE', sharePct: 11 }, { country: 'Germany', sharePct: 9 }, { country: 'Australia', sharePct: 7 }],
    avgRealisationPerKg: 6.20,
    activeExporters: 600,
    opportunityScore: 87,
    smeAccessibility: 'medium',
    minOrderValue: '₹5–15L',
    keyStates: ['Rajasthan', 'Maharashtra', 'Gujarat', 'Uttar Pradesh', 'Karnataka'],
    certifications: ['CEPC RCMC', 'FSC / PEFC Wood Sourcing Certification', 'CE Mark', 'ISO 9001', 'REACH (for surface treatments)'],
    seasonality: 'Year-round; peak orders from USA Aug–Oct for holiday restocking',
    overview: 'India is massively under-indexed in global furniture exports ($248B market) despite having wood craftsmanship, low labor cost, and design talent. Jodhpur is the world\'s largest exporter of solid mango wood furniture. IKEA\'s India sourcing program has created a cluster of certified suppliers. China+1 is rapidly shifting furniture procurement to India and Vietnam.',
    tailwinds: ['IKEA, Wayfair, Amazon Furniture actively qualifying India suppliers', 'Jodhpur furniture city gaining $2B+ in new orders (post-2022)', 'FSC-certified Indian suppliers have 0 competition from China (China lacks certification)'],
  },
]

export const SECTORS = [...new Set(EXPORT_CATEGORIES.map(c => c.sector))].sort()

export function getOpportunityBand(score: number): 'Exceptional' | 'Strong' | 'Moderate' | 'Competitive' {
  if (score >= 85) return 'Exceptional'
  if (score >= 72) return 'Strong'
  if (score >= 60) return 'Moderate'
  return 'Competitive'
}
